const EMC_AMR_REQUEST_RESP_OBJECTID = '5fa6bee8962a8fb37b1e5bce7e68ec75';
export const SPV1 = {
  _digest: (...args: any) => typeof args,
  _absorber: (...args: any) => console.log(args),
  _override: (obj: any, key: any, value: any) => (obj[key] = value),
  // devEnv() && SPV1.override(emcUsers.users['108478' as keyof object], 'drpProfileID', 3);
  _ooverride: (obj: any, key: { [key: string]: any }) => (obj = { ...obj, key }),

  TRUSTPILOT: {
    ACCESS_TOKEN1: {
      access_token: 'tpa-042c7790ce96636e1cd404cfcfb2',
      issued_at: '1741347144',
      expires_in: '360000',
      token_type: 'BearerToken',
      access:
        'eyJ0eXBlIjoiUmVzdHJpY3RlZCIsIkJ1c2luZXNzVW5pdHMiOlt7ImJ1IjoiNTkzZmFlYTEwMDAwZmYwMDA1YTQ3NjM5IiwidGllciI6IjVkZDUxMzVjZTc0NzA1MjE5OGEwOGU2YiJ9LHsiYnUiOiI0OGZiZTg5NTAwMDA2NDAwMDUwM2QyY2EiLCJ0aWVyIjoiNWRkNTEzNWNlNzQ3MDUyMTk4YTA4ZTZiIn0seyJidSI6IjY2YTk1MjYyOTQwYTUwMmZhNDYxOTBjZSIsInRpZXIiOiI1ZGQ1MTM1Y2U3NDcwNTIxOThhMDhlNmIifSx7ImJ1IjoiNTNhMDY0YjIwMDAwNjQwMDA1NzhmMTQxIiwidGllciI6IjVkZDUxMzVjZTc0NzA1MjE5OGEwOGU2YiJ9LHsiYnUiOiI2NjMwYWFhMzgwMjA2NjEzODA4MDkzZmYiLCJ0aWVyIjoiNWRkNTEzNWNlNzQ3MDUyMTk4YTA4ZTZiIn1dfQ==',
      api_key: 'jR9bKL0xASeoifpfi5zxfG5kCMScXhg9',
    },
    ACCESS_TOKEN2: {
      access_token: 'tpa-34842c2bb6dc2633e94cb837eb37',
      issued_at: '1741348528',
      expires_in: '360000',
      token_type: 'BearerToken',
      access:
        'eyJ0eXBlIjoiUmVzdHJpY3RlZCIsIkJ1c2luZXNzVW5pdHMiOlt7ImJ1IjoiNTkzZmFlYTEwMDAwZmYwMDA1YTQ3NjM5IiwidGllciI6IjVkZDUxMzVjZTc0NzA1MjE5OGEwOGU2YiJ9LHsiYnUiOiI0OGZiZTg5NTAwMDA2NDAwMDUwM2QyY2EiLCJ0aWVyIjoiNWRkNTEzNWNlNzQ3MDUyMTk4YTA4ZTZiIn0seyJidSI6IjY2YTk1MjYyOTQwYTUwMmZhNDYxOTBjZSIsInRpZXIiOiI1ZGQ1MTM1Y2U3NDcwNTIxOThhMDhlNmIifSx7ImJ1IjoiNTNhMDY0YjIwMDAwNjQwMDA1NzhmMTQxIiwidGllciI6IjVkZDUxMzVjZTc0NzA1MjE5OGEwOGU2YiJ9LHsiYnUiOiI2NjMwYWFhMzgwMjA2NjEzODA4MDkzZmYiLCJ0aWVyIjoiNWRkNTEzNWNlNzQ3MDUyMTk4YTA4ZTZiIn1dfQ==',
      api_key: 'jR9bKL0xASeoifpfi5zxfG5kCMScXhg9',
    },
    INVITE_LINK: [
      {
        id: '9c1709f0d4dc66e97f58b836f4706b00',
        url: 'https://www.trustpilot.com/evaluate-link/9c1709f0d4dc66e97f58b836f4706b00',
      },
    ],
  },

  MNTC: {
    TRAINING_PERFORMANCE: {
      '1888871195271704': [
        {
          id: '1776227665558674326',
          name: 'Certification series',
          desc: null,
          // status: 'Pending',
          status: 'In Progress',
          duration: 20,
          percentCompleted: 0,
          isDefault: true,
          lastSyncedAt: '2025-01-21T10:36:58.684Z',
          totalModules: 25,
          moduleStatus: [
            {
              status: 'Not started',
              count: 23,
              modules: [
                {
                  id: '1776228430428858135',
                  name: 'Industry Know How',
                  isCritical: false,
                  so: 2,
                },
                {
                  id: '1876177604682228623',
                  name: 'Product Overview',
                  isCritical: false,
                  so: 3,
                },
                {
                  id: '1776228494753104974',
                  name: 'Video Assessment - Communication Interview',
                  isCritical: false,
                  so: 5,
                },
                {
                  id: '1776228368812131840',
                  name: 'Airline Insider - Reading itineraries',
                  isCritical: false,
                  so: 6,
                },
                {
                  id: '1776228320206450274',
                  name: 'Mission 1: Flight Presentation',
                  isCritical: false,
                  so: 8,
                },
                {
                  id: '1776228300469834833',
                  name: 'Asaptickets.com',
                  isCritical: false,
                  so: 9,
                },
                {
                  id: '1776227830942223533',
                  name: 'Request journey A to Z',
                  isCritical: false,
                  so: 10,
                },
                {
                  id: '1776228281027008101',
                  name: 'Client Orientation 101',
                  isCritical: false,
                  so: 11,
                },
                {
                  id: '1776228256400578923',
                  name: 'Intro to client handling workflow',
                  isCritical: false,
                  so: 12,
                },
                {
                  id: '1776228236861747635',
                  name: 'Intro to CMS: Creating a new Travel Request',
                  isCritical: false,
                  so: 13,
                },
                {
                  id: '1776228212174227967',
                  name: 'Client Orientation - Greetings',
                  isCritical: false,
                  so: 14,
                },
                {
                  id: '1776228148459686083',
                  name: 'Soft Skills - First call',
                  isCritical: false,
                  so: 15,
                },
                {
                  id: '1776228120046323038',
                  name: 'First Call FAQs',
                  isCritical: false,
                  so: 16,
                },
                {
                  id: '1776228098910021457',
                  name: 'Client Orientation - Finishing a call',
                  isCritical: false,
                  so: 17,
                },
                {
                  id: '1776227746904569926',
                  name: 'First call simulation',
                  isCritical: false,
                  so: 19,
                },
                {
                  id: '1776228045362360009',
                  name: 'Pro Quote - Basics',
                  isCritical: false,
                  so: 20,
                },
                {
                  id: '1776228013497345121',
                  name: 'Price Quote',
                  isCritical: false,
                  so: 21,
                },
                {
                  id: '1776227986566825373',
                  name: 'WhatsApp, SMS, Facebook - How to use?',
                  isCritical: false,
                  so: 22,
                },
                {
                  id: '1776227854896457486',
                  name: 'Follow up basics',
                  isCritical: false,
                  so: 23,
                },
                {
                  id: '1776227966911083372',
                  name: 'How to leave the best voice message?',
                  isCritical: false,
                  so: 24,
                },
              ],
            },
            {
              status: 'In progress',
              count: 0,
              modules: [],
            },
            {
              status: 'In review',
              count: 0,
              modules: [],
            },
            {
              status: 'Done',
              count: 1,
              modules: [
                {
                  id: '514523349993434777',
                  name: 'General Knowledge Test',
                  isCritical: false,
                  so: 25,
                  status: 'Done',
                  result: 'Pass',
                  percentScore: 50.56,
                  score: 910,
                  maxScore: 1800,
                },
                {
                  id: '507999250731259134',
                  name: 'Knowledge test Nr. 3',
                  isCritical: false,
                  so: 18,
                },
                {
                  id: '507999385687172797',
                  name: 'Knowledge Test Nr.1',
                  so: 4,
                  desc: '',
                  isCritical: false,
                  status: 'Done',
                  result: 'Pass',
                  percentScore: 50.56,
                  score: 910,
                  maxScore: 1800,
                },
                {
                  id: '507999359799977001',
                  name: 'Knowledge Test Nr. 2',
                  isCritical: false,
                  so: 7,
                  status: 'Done',
                  result: 'Pass',
                  percentScore: 50.56,
                  score: 910,
                  maxScore: 1800,
                },
                {
                  id: '1776228518519777609',
                  name: 'Certification course Introduction',
                  desc: '',
                  isCritical: false,
                  status: 'Done',
                  result: 'Pass',
                  percentScore: 50.56,
                  score: 910,
                  maxScore: 1800,
                  so: 1,
                },
              ],
            },
          ],
        },
      ],
    },

    TRAINING_PERFORMANCE_PRELIVE: {
      '1811715108731371520': [
        {
          id: '1526899855350414157',
          name: 'Certification series',
          desc: null,
          status: 'In Progress',
          prelive: true,
          duration: 20,
          percentCompleted: 0,
          isDefault: true,
          lastSyncedAt: '2024-08-04T20:15:53.275Z',
          moduleStatus: [
            {
              status: 'Not started',
              count: 16,
              modules: [
                {
                  id: '1783467441075330027',
                  name: 'Day 1 Pre live',
                  desc: 'Welcome to your first day of our Pre Live Training. During this course, please watch attentively all videos. Later you will be asked to pass an assessment and submit a Mission based on those videos. ',
                  isCritical: false,
                  so: 32,
                },
                {
                  id: '510895133688896624',
                  name: 'Day 1 Pre Live. Assessment',
                  desc: 'All questions are based on Day 1 Pre live course.',
                  isCritical: false,
                  so: 33,
                },
                {
                  id: '1808789777141753825',
                  name: 'Day 1 Pre Live Practical Mission Final',
                  desc: 'Please follow the instructions.Instructions: After watching the video, go to slides attached below.For each slide, please comment on the action. What agent is doing?Note that the screenshots from the slides are from the attached video, inserted in the same order.',
                  isCritical: false,
                  so: 34,
                },
                {
                  id: '1550435352463894161',
                  name: 'Request Handling Tips',
                  desc: '',
                  isCritical: false,
                  so: 35,
                },
                {
                  id: '1635957078405747906',
                  name: 'Assessment: Hardware & Software ',
                  desc: 'Dear future Independent Travel Manager, You have come a long way, and we congratulate you on coming to this place. Another step on this journey ahead.We at DreamPort put the customer as Priority and Focus Nr. 1 - that is why it is so important that you not only have the Knowledge, but also the tools to provide excellent service. To maintain conversations with clients, and be able to work in all systems you will need for service provision, you will need to comply with requirements, that were introduced in the beginning of the application process. Requirements: Processor: CPU with benchmark score of 5000 or higher. CPU scores available here:https://www.cpubenchmark.net/mid_range_cpus.html RAM: 8 GB RAMHeadset: headset, preferably wiredOS: not less than Windows 7 / Ubuntu 16 / macOS 10.14Browser: Chrome only, not less than 106 versionNetwork: not less than 25 Mbps (connecting via Wi-Fi or mobile data is not recommended)Camera: web camera, preferably built-inBrowser: Latest version of Google Chrome should be installed on your personal computer.Task: Watch the video with instructions.Use your phone in order to film our home office set-up. It needs to be a dedicated space, where you can work undisturbed.Show on screen your equipment: laptop or PC, as well as your headset. Show your PC or laptop specifications (from Settings) on screen.Go to www.speedtest.net and run a speed test. Show it on screen.﻿A reviewer will review your submission and if all is good, you will be moved to the next step of the process. ',
                  isCritical: false,
                  so: 36,
                },
                {
                  id: '1805522333681070293',
                  name: 'Day 1 End of the day video',
                  desc: '',
                  isCritical: false,
                  so: 37,
                },
                {
                  id: '1783540047957018463',
                  name: 'Day 2 Pre Live Course',
                  desc: 'You will see a complex example of BQ worflow that leads to sale and will be provided with several scripts that will help you in the future.',
                  isCritical: false,
                  so: 38,
                },
                {
                  id: '510927192901876301',
                  name: 'Day 2 Pre live. Assessment',
                  desc: 'Please make sure you viewed all provided materials. All the questions in this Assessment are based on materials from Day 2 Pre Live course.',
                  isCritical: false,
                  so: 39,
                },
                {
                  id: '1809223301371251743',
                  name: 'Day 2 Pre Live Practical Mission Final',
                  desc: 'Submit your task as instructed below: Log in to your Trainee CMS account - https://cms.asaptickets.com. (Username: use your Mindtickle username, Password: same as Mindtickle password)Access Bonus QueueTake a request from Bonus QueueOpen ProQuoteFind an optionCopy and paste the option in below box, following the exact format requested below:Outbound flight information:Inbound flight information:Total price for all flights:Name(s) of the Operating airline:',
                  isCritical: false,
                  so: 40,
                },
                {
                  id: '1805530380798732453',
                  name: 'Day 2 End of the day video',
                  desc: '',
                  isCritical: false,
                  so: 41,
                },
                {
                  id: '1783556503177738540',
                  name: 'Day 3 Pre live',
                  desc: 'You will get to know the departments you will interact with, will learn about lead management and our lead handling standards.',
                  isCritical: false,
                  so: 42,
                },
                {
                  id: '510933824432010552',
                  name: 'Day 3 Pre live Assessment',
                  desc: 'Please make sure you viewed all provided materials. All the questions in this Assessment are based on materials from Day 3 Pre Live course.',
                  isCritical: false,
                  so: 43,
                },
                {
                  id: '1668577760832375353',
                  name: 'Dreamport Personal Data Protection Training',
                  desc: 'Personal Data is our main asset, which must be protected and well-cared-for! Dreamport clients always presume such scenarios when they entrust their data to us.\tOn the other hand, what would we do if a client\'s credit card data, address or purchase history were leaked on the internet?\tToday, protecting personal data is as important as having a lock on the door of our house.\tOur Data Protection Team has prepared a short and engaging training that explains the basics of "personal data" and how exactly we can protect it.\t\tWatch the video\tSubmit the quiz\tIf you still have any questions or concerns use the Feedback Form at the end of the course to submit.\t\tWe look forward to receiving your answers and feedback!',
                  isCritical: false,
                  so: 44,
                },
                {
                  id: '1805531017988573737',
                  name: 'Day 3 End of the day video',
                  desc: '',
                  isCritical: false,
                  so: 45,
                },
                {
                  id: '1795842646743859793',
                  name: 'DreamPort Pre-Live: Important instructions for next Training Stage',
                  desc: '',
                  isCritical: false,
                  so: 46,
                },
              ],
            },
            {
              status: 'Done',
              count: 2,
              modules: [
                {
                  id: '1784834644105265048',
                  name: 'Introduction to Pre-Live',
                  desc: '',
                  isCritical: false,
                  status: 'Done',
                  result: 'Pass',
                  percentScore: 50.56,
                  score: 910,
                  maxScore: 1800,
                  so: 31,
                },
                {
                  id: '1792504328513597697',
                  name: 'Assessment: Hardware & Software ',
                  desc: 'Welcome to your first video assignment!This is where we get to know you and what do you have to offer!Record your screen and fulfil the required tasks.IMPORTANT: All tasks have to be completed in a single video.You may re-record as many times as you like before your final submission.After the video is recorded and submitted - you may continue the program.A live representative will evaluate your submission.IMPORTANT! If you get a sufficient score in this assignment, you may continue with your program. If you do not reach a sufficient score, your access will be closed. Due to high requirements of our partners in the Travel sector, we\'re looking for skilled candidates who match the language skill requirements, as well as are very good at communication and are available to dedicateTASK 1: (up to 2 min)Introduce yourself: (name, location, work experience, education).1. Why did you decide to become an independent travel manager?2. Do you have any previous experience in Sales or Customer Service fields?3. What are your key professional strengths?4. How would this job help you to achieve your goals?6. How many hours a day and how many days a week would you prefer to work? Are there any full time commitments you currently have, that would not allow you to dedicate yourself as an Independent Travel Manager?7. In order to maximise your income, would you consider to dedicate more time to DreamPort?8. What are your preferred hours of work? Please mention your Time Zone.TASK 2IN THE SAME VIDEO: Read the following script in the most natural way you possibly can, as if you are speaking to a real customer:"That’s a great question, John. Let me tell you more about our company and what we do. You see, we have been in business for more than 20 years and annually we are arranging over 200 thousand flights to our customers both in Economy and Business classes. On top of that we are:Members of the Better Business Bureau with A+, the highest rating.Accredited by Airline Reporting Corporation and American Society of Travel Agents.Moreover, you can check customer reviews at asapticketsreviews.com, There will be links to Trustpilot, Google & Facebook reviews, and more.On top of that, we always can provide you with the airline confirmation number of your reservation before you pay for tickets. You can check at the airline’s official website or you can call them to check if everything is in order.”',
                  isCritical: false,
                  status: 'Done',
                  result: 'Fail',
                  percentScore: 50.56,
                  score: 910,
                  maxScore: 1800,
                  seq: 36,
                },
              ],
            },
          ],
        },
      ],
    },

    VERIFY_PROGRESS_TEST: [
      {
        userId: '1811715108731371520',
        userStatus: true,
        // modulesProgress: [
        //   {
        //     //   id: '465245417156660147',
        //     //   name: 'General Knowledge Test',
        //     completedAt: 'NA',
        //     status: 'Done',
        //     result: 'Pass',
        //     percentScore: 46.67,
        //     score: 700,
        //     maxScore: 1500,
        //     attemptNo: 4,
        //   },
        // ],
      },
    ],

    USER_APP_FOR_CRON_REJECT_PENDING_MODULE: [
      {
        trainingDays: 8,
        id: 4,
        uid: null,
        profileId: 4,
        hrmId: null,
        status: 10,
        photo: null,
        emcId: 126674,
        userTypeId: 1,
        cancelReason: null,
        mntcId: '1811715108731371520',
        mntcCreatedAt: '2024-07-29T20:30:14.000Z',
        mntcFailedAt: null,
        verifyToken: null,
        verifiedAt: null,
        createdAt: '2024-06-26T13:19:16.000Z',
        updatedAt: '2024-08-05T12:58:19.000Z',
        verifyAttemptCount: null,
        loginName: 'sp179',
        source: null,
        emcActive: 1,
        campaign: null,
        medium: null,
        mntcUid: 125,
        provider: 1,
        utmCampaignId: null,
        completedModuleCount: 2,
        mandatoryModuleCompletedAt: null,
        certAwardedAt: null,
        failedModuleInfo: '1765685388983581230',
        passedModuleInfo: null,
      },
    ],
  },

  EMC_AMR_REQUEST: {
    RESP_OBJECTID: {
      SUCCESS: {
        objectID: EMC_AMR_REQUEST_RESP_OBJECTID,
        result: 'ok',
        success: true,
      },
      FAILURE: {
        objectID: EMC_AMR_REQUEST_RESP_OBJECTID,
        result: '',
        success: false,
      },
    },
    RESP_AMRID: {
      SUCCESS: {
        amrId: 12345,
        amrUuid: 'mock-amruuid',
        success: true,
      },
      FAILURE: {
        amrId: null,
        amrUuid: '',
        success: false,
      },
    },
  },

  EMR_MBSR_UPDATE: {
    SUCCESS: {
      objectID: EMC_AMR_REQUEST_RESP_OBJECTID,
      error: '',
      amrUUID: 'TRAVEL-051124-59',
      amrID: 52157,
    },
    FAILURE: {
      objectID: EMC_AMR_REQUEST_RESP_OBJECTID,
      error: 'error from emc',
      amrUUID: '',
      amrID: null,
    },
  },

  ASSESSMENT_INFO: {
    id: 695297,
    name: 'assessment name',
    tests_detail: [
      {
        id: 1,
        order: 1,
        test: {
          id: 807374,
          status: 'string',
          name: 'test tag 807374',
        },
      },
      {
        id: 2,
        order: 2,
        test: {
          id: 957724,
          status: 'string',
          name: 'test tag 957724',
        },
      },
    ],
  },

  ASSESSMENT_REQUEST: {
    id: '31',
    userApplicationId: '1',
    vendorAssessmentId: '608298',
    vendorUserId: '5216331',
    hash: '0df1dfcf-3d01-4631-9ed7-63ad4f8fac31',
    maxScore: 'null',
    score: 'null',
    result: 'null',
    status: '1',
    createdAt: '2023-10-19 13:14:33.000',
    updatedAt: '2023-10-19 13:14:33.000',
  },

  ASSESSMENT_INVITE: {
    id: 6910687,
    invitation_uuid: 'f0b44c54-86d5-4ef1-8bb6-772361de2b57',
    assessment: 695297,
    email: 'firstUser1122@gmail.com',
    first_name: 'firstName',
    last_name: 'lastName',
    created: '2024-02-09T07:38:38.595648+02:00',
    testtaker_id: 5082572,
    status: 'invited',
    average: null,
    is_with_feedback_about_hired: false,
    reminder_sent: false,
    last_reminder_sent: null,
    content_type_name: 'test_taker.assessmentcandidature',
    is_hired: false,
    personality: null,
    personality_algorithm: null,
    greenhouse_profile_url: '',
    stage: 'NYE',
    status_notification: null,
  },

  SUBMITTED_ASSESSMENT_RESPONSE: {
    count: 3,
    next: null,
    previous: null,
    results: [
      {
        id: 9984099,
        invitation_uuid: '32da1f49-d649-455f-80c7-da8cb940f4b6',
        testtaker_id: 4150613,
        email: 'manojan158@gmail.com',
        full_name: 'Manoj Kumar',
        created: '2023-10-23T07:57:57.088305+02:00',
        modified: '2023-10-23T08:05:16.357693+02:00',
        last_activity: '2023-10-23T06:04:46.201214Z',
        average: 23,
        rating: null,
        is_with_feedback_about_hired: false,
        content_type_name: 'test_taker.assessmentcandidature',
        is_hired: false,
        personality: null,
        status: 'completed',
        has_consumed_credit: true,
        personality_algorithm: null,
        review: null,
        reminder_sent: false,
        last_reminder_sent: null,
        results_sent: false,
        stage: 'NYE',
        invitation_link:
          'https://assessment.testgorilla.com/testtaker/takeinvitation/6606c8d1-21fa-4423-8fc0-5b2962fb6963',
        role: 'external',
        status_notification: 'null',
        average_without_benchmark: 80,
        test_scores: [
          {
            test_id: 807374,
            score: 31,
          },
          {
            test_id: 957724,
            score: 15,
          },
        ],
        next_notification_reminder_time: 0,
      },
      {
        id: 4887115,
        email: 'ankit.jain@gmail.com',
        full_name: 'Surjeet2211141723 Verma',
        invitation_uuid: '2205967d-780c-42f5-b6b0-5f7399df7d71',
        created: '2023-09-21T12:54:36.490889+02:00',
        modified: '2023-09-21T12:58:35.330323+02:00',
        last_activity: '2023-09-21T10:58:34.061319Z',
        testtaker_id: 3905569,
        average: 24,
        rating: null,
        is_with_feedback_about_hired: false,
        content_type_name: 'test_taker.assessmentcandidature',
        is_hired: false,
        personality: null,
        status: 'completed',
        has_consumed_credit: true,
        personality_algorithm: null,
        review: null,
        reminder_sent: false,
        last_reminder_sent: null,
        results_sent: false,
        stage: 'NYE',
        invitation_link:
          'https://assessment.testgorilla.com/testtaker/takeinvitation/2205967d-780c-42f5-b6b0-5f7399df7d71',
        role: 'external',
        status_notification: 'delivered',
        average_without_benchmark: 24,
        test_scores: [
          {
            test_id: 60078,
            score: 18,
          },
          {
            test_id: 895115,
            score: 31,
          },
          {
            test_id: 1295618,
            score: null,
          },
        ],
        next_notification_reminder_time: 0,
      },
      {
        id: 4884017,
        email: 'a.bansal@gmail.com',
        full_name: 'Surjeet2209271203 Verma',
        invitation_uuid: '3d592c21-0350-486f-86ea-73be02d2344f',
        created: '2023-09-21T09:11:02.273730+02:00',
        modified: '2023-10-09T15:02:17.243025+02:00',
        last_activity: '2023-10-09T13:02:04.133709Z',
        testtaker_id: 3903512,
        average: 23,
        rating: null,
        is_with_feedback_about_hired: false,
        content_type_name: 'test_taker.assessmentcandidature',
        is_hired: false,
        personality: null,
        status: 'completed',
        has_consumed_credit: true,
        personality_algorithm: null,
        review: null,
        reminder_sent: true,
        last_reminder_sent: '2023-09-23T09:34:58.541104+02:00',
        results_sent: false,
        stage: 'NYE',
        invitation_link:
          'https://assessment.testgorilla.com/testtaker/takeinvitation/3d592c21-0350-486f-86ea-73be02d2344f',
        role: 'external',
        status_notification: 'delivered',
        average_without_benchmark: 23,
        test_scores: [
          {
            test_id: 60078,
            score: 0,
          },
          {
            test_id: 895115,
            score: 46,
          },
          {
            test_id: 1295618,
            score: null,
          },
        ],
        next_notification_reminder_time: 0,
      },
    ],
  },

  EMC_UPDATE: {
    users: {
      '265222': {
        name: 'Ravi Kaushik',
        mindtickleId: '6b5eb189ee218',
        // mindtickleId: null,
        drpProfileID: '51643',
        id: '265222',
        emcId: '265222',
        login: 'rk190',
        displayName: 'rk190',
        teamId: '1182',
        isActive: '1',
        location: {
          id: 24,
          name: 'drp',
          label: 'DRP',
        },
        hrmId: null,
        sfId: null,
        createTime: '2025-02-10 08:42:36',
        sourceId: '265222',
        employeeId: '70005',
        dmsId: null,
        statusId: '2',
        sfUserId: null,
        msId: null,
        hasAccountInBackOffice: false,
        gender: 'Male',
        accountType: null,
        jiraEmail: [],
        position: {
          department: null,
          occupation: null,
          hrmEmployerId: null,
          hrmPosition: null,
          sapPosition: null,
          drpPosition: {
            id: 1,
            name: 'Independent Travel Manager',
          },
          drpDepartment: {
            id: 1,
            name: 'Independent Travel Manager',
          },
        },
        phones: [
          {
            uid: 'LTODVPTDNKJ',
            mask: '9189******97',
            isPrimary: true,
            type: 'mobile',
          },
        ],
        photos: [],
        groups: [],
        roles: [],
        settings: {
          startWorkOnFloorDt: '2025-02-07 00:00:00',
          isTGAgent: '1',
        },
        companySettings: {
          Training: {
            voipDirect: null,
          },
          Personal: {
            email: {
              uid: '2MBDCMD8XWP',
              mask: 'trr**********@gmail.com',
            },
            defaultEmail: true,
            voipDirect: null,
          },
        },
        availableCompanies: {
          '32': 'Training',
        },
        projectGroups: [],
        devices: [],
        project_id: 362,
        project_name: 'DRPT',
      },
    },
  },

  TRAINING_PERFORMANCE: {
    '1696116281262407680': [
      {
        id: '1526899855350414157',
        name: 'Certification series',
        desc: 'null',
        status: 'In Progress',
        duration: 20,
        percentCompleted: 66.67,
        lastSyncedAt: '2024-03-27T16:11:41.000Z',
        moduleStatus: [
          {
            status: 'Not started',
            count: 20,
            modules: [
              {
                id: '1636018608874019812',
                name: 'Certification course Introduction',
                desc: 'This Introductory Online course is provided is designed to evaluate your existing skills and abilities, as well as to introduce you to all aspects of a travel specialists role.\t\tIntroduction\tWho are we looking for? \tPerks of being an independent travel consultant\t',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1526901978293431702',
                name: 'Industry Know How',
                desc: 'This course will be your guide to the industry of passenger air travel, and your future role as a travel agent in it. In this course you will learn:\t\tHow airline distribution works? \tWhat is a Travel Consultants role? \tPoint to point vs Hub, spokes and gateways\tFlight types and Trip types\tClasses of service and booking codes\tOTA and meta search engines - benefits and downsides\tHow to conduct a proper flight search? \tOne way vs Round trip\tTransits, layover, flight duration\tBaggage allowance\tWhat determines a good flight?\t',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1572878489965222314',
                name: 'Knowledge Test Nr.1',
                desc: "Knoweldge Test Nr. 1 - Your knowledge of the Airline Know How & Market research topics will be tested.You will have only 30 minutes to complete the test, do not start it if you cannot finish it within 30 minutes. (Test will run even if you switch off your computer). \tIf you don't reach the cut off certificate score, you may reattempt the test 3 times only.If you do not reach the required score after 3rd attempt, unfortunately you will not be able to move forward.",
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1562386986221486759',
                name: 'Airline Insider - Reading itineraries',
                desc: 'In this course you will learn how to read flight itineraries in user friendly as well as GDS format. \tTopics for this course: \t- Time zones\t- What a flight itinerary consists of? \t- Reading itineraries - simple view\t- Reading itineraries - GDS view\t- Reading complicated itineraries - GDS view',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1576911454451910803',
                name: 'Knowledge Test Nr. 2',
                desc: "Reading Itineraries - Knowledge Test.\tYou will have only 30 minutes to complete the test, do not start it if you cannot finish it within 30 minutes. (Test will run even if you switch off your computer). \tIf you don't reach the cut off certificate score, you may reattempt the test 3 times only.If you do not reach the required score after 3rd attempt, unfortunately you will not be able to move forward.",
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1667076553791911155',
                name: 'Mission 1: Flight Presentation',
                desc: "Welcome to your first practical assignment!In this task you will need to record an audio of yourself reading a flight itinerary. You can try as many times as you want and submit your final version. An AI assistant will help you evaluate your submission, before you choose the final one and submit it.Then your submission will be evaluated by one of our training specialists.After you complete this Mission and wait for the review - you can continue your online course - the next lesson will be open for you.Task:Read the itinerary on the slide the same way you would read it for a customer. Note:Trip typeAirline companyGoing flight: departure city, date, time | arrival city, date, timeGoing flight: Are there any layovers? How many? Where? For how long?Going flight: Trip duration.Return: departure city, date, time | arrival city, date, time.Return: Are there any layovers? How many? Where? For how long?Return: Trip duration.Try to make your speech as effortless as possible, you don't want to be robotic!For example: \"This is a one way flight on United airlines. It departs from New York city  Kennedy airport on the 6th of June, 10.15am in the morning and arrives to the final destination - London, 9PM same evening.  There's a short layover in Frankfurt, Germany on the way for 3 hours and 20 minutes. Total duration is 10 hours. The return flight is on the 25th of August, it departs from London 12PM in the afternoon and arrives  back to New York on the 26th of August 7am in the morning. There are no stops on the way,Evaluation: Check your submission, if you wish, you may re-record it. After that it will be evaluated by a training professional.Trainer will check:That there are minimum 2 flight options found.That the options match the requirements.That the explanations you provided about the travel options are correct.That the explanations you provided about the options are brief, but contain all the important details.That the options are actually the best ones available.That the explanations why the options are the best are sensible, logic",
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1530168682366403366',
                name: 'Asaptickets.com',
                desc: '',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1572878760233118608',
                name: 'Intro to client handling workflow',
                desc: '',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1575801965008152408',
                name: 'Intro to CMS: Creating a new Travel Request',
                desc: '',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1531175950609597399',
                name: 'Soft Skills - First call',
                desc: 'In this module you will learn: \t- How to handle the first call with a client\t- What information to collect? \t- Collecting trip details and preferences\t- Frequently asked questions\t- How to explain advertised fares',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1580870645681606554',
                name: 'First Call FAQs',
                desc: 'In this course, you will learn about the frequently asked questions on the first call and how to answer them in the most correct, clear, and professional manner.\tThe main topics will be: \t\tFAQ - Questions about our company\tFAQ - Advertised prices\tFAQ - How to explain advertised prices\tFAQ - Other frequent questions\tFeedback \t',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1577980015323864486',
                name: 'Knowledge test Nr. 3',
                desc: "Knowledge test Nr. 3 - General knowledge.\tYou will have only 30 minutes to complete the test, do not start it if you cannot finish it within 30 minutes. (Test will run even if you switch off your computer). \tIf you don't reach the cut off certificate score, you may reattempt the test 3 times only.If you do not reach the required score after 3rd attempt, unfortunately you will not be able to move forward.",
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1590660775512082434',
                name: 'Price Quote',
                desc: 'In this course, you will learn what it is a Price Quote, its main and secondary functions.\tTopics covered:\t\tWhat is a Price Quote?\tAdding a PQ  from Pro Quote.\tSending PQs.\tOther PQ features.\tFeedback\t',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1564944258134055178',
                name: 'WhatsApp, SMS, Facebook - How to use?',
                desc: '',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1537447296067453233',
                name: 'How to leave the best voice message?',
                desc: '',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1537431395982263244',
                name: 'Fare Lock guide',
                desc: '',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1694688980808204531',
                name: 'Travel Care Service 3.0 | 4.0',
                desc: 'This course will cover one of the most useful products for our clients - Travel Care Service  3.0 | 4.0 versions. In the time when travel plans can change any minute it brings peace of mind and helps save money and time to our customers.\tTopics:\t\tProduct Overview\tTiers - basic, premium, all included\tBenefits\tRules and restrictions\tSales strategies\tBest examples\t',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1753398935644959278',
                name: 'Practical Mission: Present Travel Care Service',
                desc: 'null',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1696496057357372953',
                name: 'Lost Baggage Protection',
                desc: '',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1732529065224971855',
                name: 'Follow up basics',
                desc: 'null',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
            ],
          },
          {
            status: 'In progress',
            count: 3,
            modules: [
              {
                id: '1765685388983581230',
                name: 'Video Assessment - Communication Interview',
                desc: 'null',
                isCritical: true,
                status: 'In progress',
                result: null,
                percentScore: null,
                score: 0,
                maxScore: 0,
              },
              {
                id: '1550435352463894161',
                name: 'Request Handling Tips',
                desc: 'null',
                isCritical: false,
                status: 'In progress',
                result: null,
                percentScore: 60.67,
                score: 455,
                maxScore: 750,
              },
              {
                id: '1651555098625835670',
                name: 'Soft Phone in CMS',
                desc: 'null',
                isCritical: false,
                status: 'In progress',
                result: null,
                percentScore: 51.11,
                score: 230,
                maxScore: 450,
              },
            ],
          },
          {
            status: 'In review',
            count: 0,
            modules: [],
          },
          {
            status: 'Done',
            count: 10,
            modules: [
              {
                id: '1530203191469586028',
                name: 'Client Orientation 101',
                desc: '',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 100,
                score: 600,
                maxScore: 600,
              },
              {
                id: '1530208502174908343',
                name: 'Client Orientation - Greetings',
                desc: '',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 89.07,
                score: 668,
                maxScore: 750,
              },
              {
                id: '1539233505793140658',
                name: 'Client Orientation - Finishing a call',
                desc: '',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 100,
                score: 600,
                maxScore: 600,
              },
              {
                id: '1547906251005771827',
                name: 'Pro Quote - Basics',
                desc: '',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 100,
                score: 700,
                maxScore: 700,
              },
              {
                id: '1539201414813982284',
                name: 'Request journey A to Z',
                desc: 'null',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 78,
                score: 780,
                maxScore: 1000,
              },
              {
                id: '1631579770300313840',
                name: 'Rules 2023: Standards of Lead handling',
                desc: 'null',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 100,
                score: 650,
                maxScore: 650,
              },
              {
                id: '1631596174682689382',
                name: 'Rules 2023: Standards of lead handling Assessment',
                desc: 'null',
                isCritical: true,
                status: 'Done',
                result: 'Fail',
                percentScore: 58.82,
                score: 1000,
                maxScore: 1700,
              },
              {
                id: '1541443020029688981',
                name: 'First call simulation',
                desc: 'null',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 98.67,
                score: 592,
                maxScore: 600,
              },
              {
                id: '1668577760832375353',
                name: 'Dreamport Personal Data Protection Training',
                desc: 'null',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 100,
                score: 950,
                maxScore: 950,
              },
              {
                id: '1635957078405747906',
                name: 'Assessment: Hardware & Software ',
                desc: 'Welcome to your first video assignment!This is where we get to know you and what do you have to offer!Record your screen and fulfil the required tasks.IMPORTANT: All tasks have to be completed in a single video.You may re-record as many times as you like before your final submission.After the video is recorded and submitted - you may continue the program.A live representative will evaluate your submission.IMPORTANT! If you get a sufficient score in this assignment, you may continue with your program. If you do not reach a sufficient score, your access will be closed. Due to high requirements of our partners in the Travel sector, we\'re looking for skilled candidates who match the language skill requirements, as well as are very good at communication and are available to dedicateTASK 1: (up to 2 min)Introduce yourself: (name, location, work experience, education).1. Why did you decide to become an independent travel manager?2. Do you have any previous experience in Sales or Customer Service fields?3. What are your key professional strengths?4. How would this job help you to achieve your goals?6. How many hours a day and how many days a week would you prefer to work? Are there any full time commitments you currently have, that would not allow you to dedicate yourself as an Independent Travel Manager?7. In order to maximise your income, would you consider to dedicate more time to DreamPort?8. What are your preferred hours of work? Please mention your Time Zone.TASK 2IN THE SAME VIDEO: Read the following script in the most natural way you possibly can, as if you are speaking to a real customer:"That’s a great question, John. Let me tell you more about our company and what we do. You see, we have been in business for more than 20 years and annually we are arranging over 200 thousand flights to our customers both in Economy and Business classes. On top of that we are:Members of the Better Business Bureau with A+, the highest rating.Accredited by Airline Reporting Corporation and American Society of Travel Agents.Moreover, you can check customer reviews at asapticketsreviews.com, There will be links to Trustpilot, Google & Facebook reviews, and more.On top of that, we always can provide you with the airline confirmation number of your reservation before you pay for tickets. You can check at the airline’s official website or you can call them to check if everything is in order.”',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 62.86,
                score: 880,
                maxScore: 1400,
              },
            ],
          },
        ],
      },
    ],
    '1728764349244940288': [
      {
        id: '1526899855350414157',
        name: 'Certification series',
        desc: 'null',
        status: 'In Progress',
        duration: 20,
        percentCompleted: 96.67,
        lastSyncedAt: '2024-03-22T07:50:12.000Z',
        moduleStatus: [
          {
            status: 'Not started',
            count: 4,
            modules: [
              {
                id: '1765685388983581230',
                name: 'Video Assessment - Communication Interview',
                desc: 'null',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1753398935644959278',
                name: 'Practical Mission: Present Travel Care Service',
                desc: 'null',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1732529065224971855',
                name: 'Follow up basics',
                desc: 'null',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
              {
                id: '1668577760832375353',
                name: 'Dreamport Personal Data Protection Training',
                desc: 'null',
                isCritical: false,
                status: 'Not started',
                result: null,
                percentScore: null,
                score: null,
                maxScore: null,
              },
            ],
          },
          {
            status: 'In progress',
            count: 0,
            modules: [],
          },
          {
            status: 'In review',
            count: 0,
            modules: [],
          },
          {
            status: 'Done',
            count: 29,
            modules: [
              {
                id: '1636018608874019812',
                name: 'Certification course Introduction',
                desc: 'This Introductory Online course is provided is designed to evaluate your existing skills and abilities, as well as to introduce you to all aspects of a travel specialists role.\t\tIntroduction\tWho are we looking for? \tPerks of being an independent travel consultant\t',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 100,
                score: 750,
                maxScore: 750,
              },
              {
                id: '1526901978293431702',
                name: 'Industry Know How',
                desc: 'This course will be your guide to the industry of passenger air travel, and your future role as a travel agent in it. In this course you will learn:\t\tHow airline distribution works? \tWhat is a Travel Consultants role? \tPoint to point vs Hub, spokes and gateways\tFlight types and Trip types\tClasses of service and booking codes\tOTA and meta search engines - benefits and downsides\tHow to conduct a proper flight search? \tOne way vs Round trip\tTransits, layover, flight duration\tBaggage allowance\tWhat determines a good flight?\t',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 98.48,
                score: 2846,
                maxScore: 2890,
              },
              {
                id: '1572878489965222314',
                name: 'Knowledge Test Nr.1',
                desc: "Knoweldge Test Nr. 1 - Your knowledge of the Airline Know How & Market research topics will be tested.You will have only 30 minutes to complete the test, do not start it if you cannot finish it within 30 minutes. (Test will run even if you switch off your computer). \tIf you don't reach the cut off certificate score, you may reattempt the test 3 times only.If you do not reach the required score after 3rd attempt, unfortunately you will not be able to move forward.",
                isCritical: true,
                status: 'Done',
                result: 'Fail',
                percentScore: 60,
                score: 900,
                maxScore: 1500,
              },
              {
                id: '1562386986221486759',
                name: 'Airline Insider - Reading itineraries',
                desc: 'In this course you will learn how to read flight itineraries in user friendly as well as GDS format. \tTopics for this course: \t- Time zones\t- What a flight itinerary consists of? \t- Reading itineraries - simple view\t- Reading itineraries - GDS view\t- Reading complicated itineraries - GDS view',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 83.87,
                score: 3858,
                maxScore: 4600,
              },
              {
                id: '1576911454451910803',
                name: 'Knowledge Test Nr. 2',
                desc: "Reading Itineraries - Knowledge Test.\tYou will have only 30 minutes to complete the test, do not start it if you cannot finish it within 30 minutes. (Test will run even if you switch off your computer). \tIf you don't reach the cut off certificate score, you may reattempt the test 3 times only.If you do not reach the required score after 3rd attempt, unfortunately you will not be able to move forward.",
                isCritical: true,
                status: 'Done',
                result: 'Fail',
                percentScore: 73.33,
                score: 1100,
                maxScore: 1500,
              },
              {
                id: '1667076553791911155',
                name: 'Mission 1: Flight Presentation',
                desc: "Welcome to your first practical assignment!In this task you will need to record an audio of yourself reading a flight itinerary. You can try as many times as you want and submit your final version. An AI assistant will help you evaluate your submission, before you choose the final one and submit it.Then your submission will be evaluated by one of our training specialists.After you complete this Mission and wait for the review - you can continue your online course - the next lesson will be open for you.Task:Read the itinerary on the slide the same way you would read it for a customer. Note:Trip typeAirline companyGoing flight: departure city, date, time | arrival city, date, timeGoing flight: Are there any layovers? How many? Where? For how long?Going flight: Trip duration.Return: departure city, date, time | arrival city, date, time.Return: Are there any layovers? How many? Where? For how long?Return: Trip duration.Try to make your speech as effortless as possible, you don't want to be robotic!For example: \"This is a one way flight on United airlines. It departs from New York city  Kennedy airport on the 6th of June, 10.15am in the morning and arrives to the final destination - London, 9PM same evening.  There's a short layover in Frankfurt, Germany on the way for 3 hours and 20 minutes. Total duration is 10 hours. The return flight is on the 25th of August, it departs from London 12PM in the afternoon and arrives  back to New York on the 26th of August 7am in the morning. There are no stops on the way,Evaluation: Check your submission, if you wish, you may re-record it. After that it will be evaluated by a training professional.Trainer will check:That there are minimum 2 flight options found.That the options match the requirements.That the explanations you provided about the travel options are correct.That the explanations you provided about the options are brief, but contain all the important details.That the options are actually the best ones available.That the explanations why the options are the best are sensible, logic",
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 75,
                score: 900,
                maxScore: 1200,
              },
              {
                id: '1530168682366403366',
                name: 'Asaptickets.com',
                desc: '',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 86.25,
                score: 690,
                maxScore: 800,
              },
              {
                id: '1530203191469586028',
                name: 'Client Orientation 101',
                desc: '',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 100,
                score: 600,
                maxScore: 600,
              },
              {
                id: '1572878760233118608',
                name: 'Intro to client handling workflow',
                desc: '',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 99.09,
                score: 1090,
                maxScore: 1100,
              },
              {
                id: '1575801965008152408',
                name: 'Intro to CMS: Creating a new Travel Request',
                desc: '',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 100,
                score: 350,
                maxScore: 350,
              },
              {
                id: '1530208502174908343',
                name: 'Client Orientation - Greetings',
                desc: '',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 100,
                score: 750,
                maxScore: 750,
              },
              {
                id: '1531175950609597399',
                name: 'Soft Skills - First call',
                desc: 'In this module you will learn: \t- How to handle the first call with a client\t- What information to collect? \t- Collecting trip details and preferences\t- Frequently asked questions\t- How to explain advertised fares',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 86.7,
                score: 3468,
                maxScore: 4000,
              },
              {
                id: '1580870645681606554',
                name: 'First Call FAQs',
                desc: 'In this course, you will learn about the frequently asked questions on the first call and how to answer them in the most correct, clear, and professional manner.\tThe main topics will be: \t\tFAQ - Questions about our company\tFAQ - Advertised prices\tFAQ - How to explain advertised prices\tFAQ - Other frequent questions\tFeedback \t',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 96.11,
                score: 1730,
                maxScore: 1800,
              },
              {
                id: '1539233505793140658',
                name: 'Client Orientation - Finishing a call',
                desc: '',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 100,
                score: 600,
                maxScore: 600,
              },
              {
                id: '1577980015323864486',
                name: 'Knowledge test Nr. 3',
                desc: "Knowledge test Nr. 3 - General knowledge.\tYou will have only 30 minutes to complete the test, do not start it if you cannot finish it within 30 minutes. (Test will run even if you switch off your computer). \tIf you don't reach the cut off certificate score, you may reattempt the test 3 times only.If you do not reach the required score after 3rd attempt, unfortunately you will not be able to move forward.",
                isCritical: true,
                status: 'Done',
                result: 'Fail',
                percentScore: 75,
                score: 1500,
                maxScore: 2000,
              },
              {
                id: '1547906251005771827',
                name: 'Pro Quote - Basics',
                desc: '',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 91.43,
                score: 640,
                maxScore: 700,
              },
              {
                id: '1590660775512082434',
                name: 'Price Quote',
                desc: 'In this course, you will learn what it is a Price Quote, its main and secondary functions.\tTopics covered:\t\tWhat is a Price Quote?\tAdding a PQ  from Pro Quote.\tSending PQs.\tOther PQ features.\tFeedback\t',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 91.57,
                score: 1923,
                maxScore: 2100,
              },
              {
                id: '1564944258134055178',
                name: 'WhatsApp, SMS, Facebook - How to use?',
                desc: '',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 97.73,
                score: 1075,
                maxScore: 1100,
              },
              {
                id: '1537447296067453233',
                name: 'How to leave the best voice message?',
                desc: '',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 86,
                score: 430,
                maxScore: 500,
              },
              {
                id: '1537431395982263244',
                name: 'Fare Lock guide',
                desc: '',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 100,
                score: 1000,
                maxScore: 1000,
              },
              {
                id: '1694688980808204531',
                name: 'Travel Care Service 3.0 | 4.0',
                desc: 'This course will cover one of the most useful products for our clients - Travel Care Service  3.0 | 4.0 versions. In the time when travel plans can change any minute it brings peace of mind and helps save money and time to our customers.\tTopics:\t\tProduct Overview\tTiers - basic, premium, all included\tBenefits\tRules and restrictions\tSales strategies\tBest examples\t',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 100,
                score: 950,
                maxScore: 950,
              },
              {
                id: '1696496057357372953',
                name: 'Lost Baggage Protection',
                desc: '',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 100,
                score: 300,
                maxScore: 300,
              },
              {
                id: '1539201414813982284',
                name: 'Request journey A to Z',
                desc: 'null',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 86.7,
                score: 867,
                maxScore: 1000,
              },
              {
                id: '1631579770300313840',
                name: 'Rules 2023: Standards of Lead handling',
                desc: 'null',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 76.92,
                score: 500,
                maxScore: 650,
              },
              {
                id: '1631596174682689382',
                name: 'Rules 2023: Standards of lead handling Assessment',
                desc: 'null',
                isCritical: false,
                status: 'Done',
                result: 'Fail',
                percentScore: 82.35,
                score: 1400,
                maxScore: 1700,
              },
              {
                id: '1550435352463894161',
                name: 'Request Handling Tips',
                desc: 'null',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 89.6,
                score: 672,
                maxScore: 750,
              },
              {
                id: '1541443020029688981',
                name: 'First call simulation',
                desc: 'null',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 93,
                score: 558,
                maxScore: 600,
              },
              {
                id: '1651555098625835670',
                name: 'Soft Phone in CMS',
                desc: 'null',
                isCritical: false,
                status: 'Done',
                result: 'Pass',
                percentScore: 97.78,
                score: 440,
                maxScore: 450,
              },
              {
                id: '1635957078405747906',
                name: 'Assessment: Hardware & Software ',
                desc: 'Welcome to your first video assignment!This is where we get to know you and what do you have to offer!Record your screen and fulfil the required tasks.IMPORTANT: All tasks have to be completed in a single video.You may re-record as many times as you like before your final submission.After the video is recorded and submitted - you may continue the program.A live representative will evaluate your submission.IMPORTANT! If you get a sufficient score in this assignment, you may continue with your program. If you do not reach a sufficient score, your access will be closed. Due to high requirements of our partners in the Travel sector, we\'re looking for skilled candidates who match the language skill requirements, as well as are very good at communication and are available to dedicateTASK 1: (up to 2 min)Introduce yourself: (name, location, work experience, education).1. Why did you decide to become an independent travel manager?2. Do you have any previous experience in Sales or Customer Service fields?3. What are your key professional strengths?4. How would this job help you to achieve your goals?6. How many hours a day and how many days a week would you prefer to work? Are there any full time commitments you currently have, that would not allow you to dedicate yourself as an Independent Travel Manager?7. In order to maximise your income, would you consider to dedicate more time to DreamPort?8. What are your preferred hours of work? Please mention your Time Zone.TASK 2IN THE SAME VIDEO: Read the following script in the most natural way you possibly can, as if you are speaking to a real customer:"That’s a great question, John. Let me tell you more about our company and what we do. You see, we have been in business for more than 20 years and annually we are arranging over 200 thousand flights to our customers both in Economy and Business classes. On top of that we are:Members of the Better Business Bureau with A+, the highest rating.Accredited by Airline Reporting Corporation and American Society of Travel Agents.Moreover, you can check customer reviews at asapticketsreviews.com, There will be links to Trustpilot, Google & Facebook reviews, and more.On top of that, we always can provide you with the airline confirmation number of your reservation before you pay for tickets. You can check at the airline’s official website or you can call them to check if everything is in order.”',
                isCritical: true,
                status: 'Done',
                result: 'Pass',
                percentScore: 81.67,
                score: 1470,
                maxScore: 1800,
              },
            ],
          },
        ],
      },
    ],
  },

  TRAINING_SEED_USER: {
    added: [{ userId: '1888871195271704', uid: 727 }],
    exists: [],
  },

  EXISTING_EMPLOYEE: {
    SAP: {
      root: {
        success: true,
        data: {
          User: [
            {
              globalPersonUID: '10002459',
              userId: '10002459',
              location: {
                externalCode: 'DEL',
                name: 'Delhi',
              },
              company: {
                externalCode: '25',
                name: 'Dyninno India LLP',
              },
              position: {
                externalCode: '13218',
                name: 'Dreamport Product Engineering Senior Developer',
              },
              employeeType: {
                externalCode: 'employee',
                name: 'Employee',
              },
              contractType: {
                externalCode: 'employee',
                name: 'Employee contract',
              },
              status: 'ACTIVE',
              email: 'surjeet.verma@dyninno.in',
              personState: 'EMPLOYEE',
            },
          ],
        },
      },
    },
    SAP_EX_EMP: {
      root: {
        success: true,
        data: {
          User: [
            {
              globalPersonUID: '20006513',
              userId: '30002341',
              location: {
                externalCode: 'DEL',
                name: 'Delhi',
              },
              company: {
                externalCode: '54',
                name: 'Technical Legal Entity',
              },
              position: {
                externalCode: '11020',
                name: 'Senior Developer',
              },
              employeeType: {
                externalCode: 'employee',
                name: 'Employee',
              },
              contractType: {
                externalCode: 'employee',
                name: 'Employee contract',
              },
              status: 'INACTIVE',
              email: 'thakur.shikha3005@gmail.com',
              personState: 'EMPLOYEE',
            },
          ],
        },
      },
    },
    HRM: {
      freelanceCheck: false,
      employmentCheck: true,
    },
  },
};

// update counts of training-performance
Object.keys(SPV1.MNTC.TRAINING_PERFORMANCE).forEach((key: string) => {
  const moduleStatus: any = SPV1.MNTC.TRAINING_PERFORMANCE[key as keyof object][0]['moduleStatus'];
  moduleStatus.forEach((element: any) => {
    // console.log(element, index);
    element.count = element.modules.length;
  });
});

export const emc_data = {
  users: {
    '118999': {
      name: 'Ruslans Zubenko',
      location: {
        id: 34,
        name: 'Test',
        label: 'TES',
      },
      hrmId: null,
      sfId: '10000922',
      id: '118999',
      emcId: '118999',
      login: 'r.zubenko',
      displayName: 'Ruslans Zubenko',
      teamId: '2014',
      isActive: '1',
      createTime: '2023-01-25 12:56:14',
      sourceId: '118999',
      employeeId: '43084',
      dmsId: null,
      statusId: '2',
      sfUserId: '10000922',
      msId: null,
      hasAccountInBackOffice: false,
      mindtickleId: null,
      drpProfileID: null,
      gender: 'Male',
      accountType: null,
      jiraEmail: [],
      position: {
        department: null,
        occupation: null,
        hrmEmployerId: null,
        hrmPosition: null,
        sapPosition: {
          id: '160',
          name: 'QA Travel IT',
          sapEmployerId: '5',
          groupId: 1494,
        },
        drpPosition: null,
        drpDepartment: null,
      },
      phones: [
        {
          uid: 'EPY22BWPEO6',
          mask: '3712*****67',
          isPrimary: true,
          type: 'mobile',
        },
      ],
      photos: [],
      groups: [
        {
          id: 5980,
          name: 'Developer',
          project: true,
        },
      ],
      roles: ['login'],
      settings: {
        isSLTagent: '0',
        ageInMonths: '4',
        gds_direct_fs_limit: '0',
        isBogAgent: '0',
        isDelAgent: '0',
        isAsiaAgent: '0',
        isTemporaryHomeAgent: '1',
        isTASAgent: '0',
        startWorkOnFloorDt: '2023-01-25 12:53:42',
        fullAccessToTeam: '1',
      },
      companySettings: {
        SLT: {
          voipDirect: null,
        },
        ITN: {
          email: {
            uid: '1Q02VZ07JA5',
            mask: 'j.d*****@asaptickets.com',
          },
          voipDirect: null,
        },
        UK: {
          voipDirect: null,
        },
        CA: {
          voipDirect: null,
        },
        BOG: {
          voipDirect: null,
        },
        ME: {
          voipDirect: null,
        },
        PH: {
          voipDirect: null,
        },
        Training: {
          voipDirect: null,
        },
        DXF: {
          voipDirect: null,
        },
        MNL: {
          voipDirect: null,
        },
        Vacation: {
          voipDirect: null,
        },
        Africa: {
          voipDirect: null,
        },
        DEL: {
          voipDirect: null,
        },
        ASIA: {
          voipDirect: null,
        },
        Oojo: {
          defaultEmail: true,
          voipDirect: null,
        },
        Personal: {
          email: {
            uid: '1MKXK63BXYB',
            mask: 'rus***********@gmail.com',
          },
          voipDirect: null,
        },
      },
      availableCompanies: {
        '2': 'SLT',
        '3': 'ITN',
        '11': 'UK',
        '22': 'CA',
        '24': 'BOG',
        '26': 'ME',
        '28': 'PH',
        '32': 'Training',
        '46': 'DXF',
        '56': 'MNL',
        '58': 'Vacation',
        '60': 'Africa',
        '62': 'DEL',
        '64': 'ASIA',
        '66': 'Oojo',
      },
    },
    '124759': {
      id: '124759',
      employeeId: '67163',
      teamId: '1182',
      login: 'lk134',
      displayName: 'lk126',
      name: 'loadtest_xtocr kdhdu',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-16 23:59:59',
      },
    },
    '124761': {
      id: '124761',
      employeeId: '67165',
      teamId: '1182',
      login: 'li142',
      displayName: 'li132',
      name: 'loadtest_sxhtm iqzbv',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-16 23:59:59',
      },
    },
    '124762': {
      id: '124762',
      employeeId: '67166',
      teamId: '1182',
      login: 'ls170',
      displayName: 'ls163',
      name: 'loadtest_zdksp snery',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-16 23:59:59',
      },
    },
    '124763': {
      id: '124763',
      employeeId: '67167',
      teamId: '1182',
      login: 'lm168',
      displayName: 'lm165',
      name: 'loadtest_mcwyb mtcux',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-16 23:59:59',
      },
    },
    '124764': {
      id: '124764',
      employeeId: '67168',
      teamId: '1182',
      login: 'lv135',
      displayName: 'lv130',
      name: 'loadtest_ngymd vdtzw',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-16 23:59:59',
      },
    },
    '124766': {
      id: '124766',
      employeeId: '67170',
      teamId: '1182',
      login: 'lx128',
      displayName: 'lx119',
      name: 'loadtest_rpjjm xavqg',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-16 23:59:59',
      },
    },
    '124767': {
      id: '124767',
      employeeId: '67171',
      teamId: '1182',
      login: 'lf138',
      displayName: 'lf131',
      name: 'loadtest_cuavs fkosg',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-16 23:59:59',
      },
    },
    '124768': {
      id: '124768',
      employeeId: '67172',
      teamId: '1182',
      login: 'lh135',
      displayName: 'lh125',
      name: 'loadtest_cdqwl hoktm',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-15 23:59:59',
      },
    },
    '124769': {
      id: '124769',
      employeeId: '67173',
      teamId: '1182',
      login: 'ly127',
      displayName: 'ly119',
      name: 'loadtest_hvezz yuqmd',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-15 23:59:59',
      },
    },
    '124770': {
      id: '124770',
      employeeId: '67174',
      teamId: '1182',
      login: 'lk135',
      displayName: 'lk126',
      name: 'loadtest_snkla kdlbh',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-15 23:59:59',
      },
    },
    '124771': {
      id: '124771',
      employeeId: '67175',
      teamId: '1182',
      login: 'lr149',
      displayName: 'lr143',
      name: 'loadtest_ipfnu rvyzs',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-15 23:59:59',
      },
    },
    '124772': {
      id: '124772',
      employeeId: '67176',
      teamId: '1182',
      login: 'lo141',
      displayName: 'lo129',
      name: 'loadtest_sjwby odvdg',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-15 23:59:59',
      },
    },
    '124773': {
      id: '124773',
      employeeId: '67177',
      teamId: '1182',
      login: 'ly128',
      displayName: 'ly119',
      name: 'loadtest_ejppa yctvg',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-16 23:59:59',
      },
    },
    '124774': {
      id: '124774',
      employeeId: '67178',
      teamId: '1182',
      login: 'la159',
      displayName: 'la156',
      name: 'loadtest_svnba aasgg',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-15 23:59:59',
      },
    },
    '124775': {
      id: '124775',
      employeeId: '67179',
      teamId: '1182',
      login: 'lf139',
      displayName: 'lf131',
      name: 'loadtest_bsbpu febtm',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-15 23:59:59',
      },
    },
    '124776': {
      id: '124776',
      employeeId: '67180',
      teamId: '1182',
      login: 'ln133',
      displayName: 'ln125',
      name: 'loadtest_vzlfd nvmfy',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-16 23:59:59',
      },
    },
    '124777': {
      id: '124777',
      employeeId: '67181',
      teamId: '1182',
      login: 'lq124',
      displayName: 'lq117',
      name: 'loadtest_chjva qkifc',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-16 23:59:59',
      },
    },
    '124784': {
      id: '124784',
      employeeId: '67188',
      teamId: '1182',
      login: 'lt154',
      displayName: 'lt147',
      name: 'loadtest_yggrq tyjkm',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-15 23:59:59',
      },
    },
    '124787': {
      id: '124787',
      employeeId: '67191',
      teamId: '1182',
      login: 'lu119',
      displayName: 'lu114',
      name: 'loadtest_adfzv ueasg',
      isActive: '0',
      availableCompanies: {
        '32': 'Training',
        '44': 'Personal',
      },
      settings: {
        unactivatedDt: '2023-11-15 23:59:59',
      },
    },
  },
};
