// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://mycutebaby.in/contest/participant/64345d75d5fd6
// @match        https://mycutebaby.in/contest/participant/643d8c9f374d0
// @icon         https://www.google.com/s2/favicons?sz=64&domain=mozilla.org
// @grant        none
// ==/UserScript==

(async function () {
  "use strict";

  let namedVote = true;

  function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  async function scroll() {
    console.log("scrolling");
    await sleep(3000);
    window.scrollTo(0, 3000);
  }
  async function fillName() {
    let control = await document.getElementById("v");
    // let control = true;
    if (control) {
      const names = [
        "Oliver",
        "Jake",
        "Noah",
        "James",
        "Jack",
        "Connor",
        "Liam",
        "John",
        "Harry",
        "Callum",
        "Mason",
        "Robert",
        "Jacob",
        "Charlie",
        "Kyle",
        "William",
        "Thomas",
        "Joe",
        "Ethan",
        "David",
        "George",
        "Reece",
        "Michael",
        "Richard",
        "Oscar",
        "Rhys",
        "Alexander",
        "Joseph",
        "Charles",
        "Amelia",
        "Emma",
        "Mary",
        "Olivia",
        "Samantha",
        "Patricia",
        "Isla",
        "Bethany",
        "Sophia",
        "Jennifer",
        "Emily",
        "Elizabeth",
        "Poppy",
        "Joanne",
        "Linda",
        "Ava",
        "Megan",
        "Mia",
        "Barbara",
        "Isabella",
        "Victoria",
        "Susan",
        "Lauren",
        "Abigail",
        "Margaret",
        "Lily",
        "Michelle",
        "Madison",
        "Jessica",
        "Sophie",
        "Tracy",
        "Charlotte",
        "Sarah",
        "Naya",
        "Ishaan",
        "Jai",
        "Inaya",
        "Amar",
        "Navi",
        "Dhruv",
        "Kanan",
        "Shyla",
        "Agastya",
        "Ananya",
        "Nila",
        "Tenzin",
        "Tamia",
        "Shaan",
        "Ajay",
        "Jaya",
        "Anjali",
        "Aditi",
        "Reva",
        "Sahil",
        "Darsh",
        "Aja",
        "Ambar",
        "Deven",
        "Ishani",
        "Kavi",
        "Marjane",
        "Jasleen",
        "Ashwin",
        "Aadhira",
        "Candy",
        "Kum",
        "Salina",
        "Artha",
        "Raghav",
        "Avan",
        "Sitara",
        "Shylah",
        "Divya",
        "Varun",
        "Sona",
        "Shaila",
        "Kimaya",
        "Farid",
        "Kashvi",
        "Devi",
        "Charu",
        "Mihir",
        "Tulsi",
        "Anila",
        "Anala",
        "Vivan",
        "Amitabh",
        "Mahika",
        "Sudhir",
        "Lata",
        "Anand",
        "Akshay",
        "Akhilesh",
        "Mayur",
        "Ruchika",
        "Manu",
        "Arti",
        "Janitra",
        "Tej",
        "Damayanti",
        "Rupinder",
        "Chander",
        "Rikita",
        "Yanisha",
        "Tanaia",
        "Shalene",
        "Neha",
        "Shalena",
        "Prasad",
        "Shaleena",
        "Shantai",
        "Amata",
        "Drisana",
        "Hansika",
        "Pravin",
        "Tanika",
        "Rashanda",
        "Angee",
        "Shalee",
        "Rajesh",
        "Anuradha",
        "Salena",
        "Satish",
        "Jenika",
        "Jarita",
        "Neesha",
        "Pradeep",
        "Rashana",
        "Devanand",
        "Anju",
        "Indu",
        "Lanisha",
        "Alka",
        "Ranjana",
        "Monisha",
        "Ahalya",
        "Sanjiv",
        "Jayanti",
        "Lakshman",
        "Shaili",
        "Devaki",
        "Shalina",
        "Shantay",
        "Jaswinder",
        "Darsha",
        "Didi",
        "Soma",
        "Adry",
        "Banita",
        "Johar",
        "Janak",
        "Kalynda",
        "Charita",
        "Deshad",
        "Anandita",
        "Vanita",
        "Dhaval",
        "Tanay",
        "Lalit",
        "Akilesh",
        "Chandani",
        "Deval",
        "Shantee",
        "Amrit",
        "Ajeya",
        "Azha",
        "Shakeela",
        "Shanti",
        "Neena",
        "Dhara",
        "Sajan",
        "Vianca",
        "Deva",
        "Nisha",
        "Jamaica",
        "Dharma",
        "Tanaya",
        "Ishana",
        "Amulya",
        "Amisha",
        "Naman",
        "Ashish",
        "Praneel",
        "Ajit",
        "Veena",
        "Anil",
        "Devika",
        "Aradhana",
        "Anusha",
        "Kalinda",
        "Sujay",
        "Anura",
        "Sanjeev",
        "Devendra",
        "Shaylah",
        "Rukmini",
        "Nalin",
        "Rachana",
        "Juhi",
        "Ishara",
        "Eshana",
        "Anjuli",
        "Chella",
        "Sony",
        "Ruan",
        "Abhaya",
        "Alok",
        "Aakil",
        "Anjay",
        "Adhiraj",
        "Shalini",
        "Deshan",
        "Balraj",
        "Tanea",
        "Kanisha",
        "Kaeya",
        "Jenisha",
        "Niesha",
        "Janisha",
        "Valin",
        "Bhavika",
        "Apsara",
        "Nishad",
        "Mahavir",
        "Din",
        "Devraj",
        "Shila",
        "Chaitanya",
        "Niranjana",
        "Amartya",
        "Ashok",
        "Shante",
        "Shantae",
        "Jasmeet",
        "Pooja",
        "Hasina",
        "Durga",
        "Anshu",
        "Kavita",
        "Akhila",
        "Ajia",
        "Amberlie",
        "Bhumika",
        "Anaka",
        "Aija",
        "Aakav",
        "Aakesh",
        "Aamin",
        "Aanandini",
        "Aandaleeb",
        "Aatmadeva",
        "Aatmik",
        "Abhiraja",
        "Achala",
        "Bhoja",
        "Adamya",
        "Adheesha",
        "Adhideva",
        "Adhika",
        "Agilan",
        "Aharnish",
        "Ahilya",
        "Ajalaa",
        "Ajanabh",
        "Akhilendra",
        "Chintak",
        "Bhuma",
        "Amaram",
        "Amarjaa",
        "Amirthini",
        "Amoli",
        "Amul",
        "Amutha",
        "Anadi",
        "Anang",
        "Ananta",
        "Anbarasi",
        "Anbu",
        "Andal",
        "Anganaa",
        "Angayarkanni",
        "Anuka",
        "Anupa",
        "Anupriyaa",
        "Anusheela",
        "Arasu",
        "Arivazhagi",
        "Arivoli",
        "Arpana",
        "Arumugam",
        "Arungedan",
        "Arvindaa",
        "Aryabhata",
        "Ashvaghosha",
        "Ashywyn",
        "Asmee",
        "Atyaananda",
        "Avanindra",
        "Baasu",
        "Balabhadra",
        "Balakrishna",
        "Bakul",
        "Baldev",
        "Banhi",
        "Basant",
        "Beeja",
        "Bhakati",
        "Bhamini",
        "Bhanu",
        "Bhanumati",
        "Bharati",
        "Bhaskara",
        "Bhasvan",
        "Bhaswar",
        "Bhavnish",
        "Bishvajit",
        "Brahma",
        "Chahna",
        "Chaitali",
        "Chameli",
        "Chandaa",
        "Chandrabha",
        "Chandrak",
        "Chandrakant",
        "Chandrakanta",
        "Chandraraj",
        "Chandresh",
        "Chandrima",
        "Charvaka",
        "Charudatta",
        "Charumati",
        "Chiranjiv",
        "Chirayu",
        "Daivat",
        "Dharitri",
        "Damodar",
        "Danveer",
        "Dhavala",
        "Darpitaa",
        "Dayanand",
        "Dayanita",
        "Dayaram",
        "Deccan",
        "Deshal",
        "Devahuti",
        "Devak",
        "Devanesan",
        "Devdan",
        "Devmani",
        "Dhanadaa",
        "Dharinee",
        "Dhavlen",
        "Dhavlesh",
        "Dhheiba",
        "Dhimani",
        "Dinendra",
        "Dilip",
        "Dipili",
        "Draupadi",
        "Dularee",
        "Mahavira",
        "Gambhira",
        "Gulshan",
        "Hanita",
        "Harshad",
        "Himesh",
        "Jaladhi",
        "Jaladi",
        "Jalaneeli",
        "Janesh",
        "Jayashree",
        "Jayvanti",
        "Jeladhi",
        "Jeladi",
        "Joyeeta",
        "Kalindi",
        "Lahar",
        "Lalika",
        "Ninny",
        "Nameen",
        "Nikhel",
        "Nithi",
        "Pratap",
        "Rachanna",
        "Ramnath",
        "Ravanan",
        "Saarik",
        "Saariq",
        "Sagara",
        "Sananda",
        "Sarbjit",
        "Sareek",
        "Sareeq",
        "Sariq",
        "Simla",
        "Tippoo",
        "Tipu",
        "Udayan",
        "Umed",
        "Varoun",
        "Patchouli",
        "Atul",
        "Kirani",
        "Aanan",
        "Charun",
        "Devaj",
        "Harsith",
        "Purnit",
        "Balveer",
        "Banjeet",
        "Dakshesh",
        "Ekalinga",
        "Harshil",
        "Suveer",
        "Caturnana",
        "Chaganti",
        "Dabeet",
        "Dandak",
        "Farookh",
        "Jagachandra",
        "Lalam",
        "Amruta",
        "Chaaya",
        "Chavvi",
        "Damini",
        "Dayamai",
        "Geet",
        "Heena",
        "Indali",
        "Jagvi",
        "Januja",
        "Jhalak",
        "Lipika",
        "Lopa",
        "Nayantara",
        "Barir",
        "Chakra",
        "Sumana",
        "Tarana",
        "Aarna",
        "Atharv",
        "Wade",
        "Dave",
        "Seth",
        "Ivan",
        "Riley",
        "Gilbert",
        "Jorge",
        "Dan",
        "Brian",
        "Roberto",
        "Ramon",
        "Miles",
        "Liam",
        "Nathaniel",
        "Ethan",
        "Lewis",
        "Milton",
        "Claude",
        "Joshua",
        "Glen",
        "Harvey",
        "Blake",
        "Antonio",
        "Connor",
        "Julian",
        "Aidan",
        "Harold",
        "Conner",
        "Peter",
        "Hunter",
        "Eli",
        "Alberto",
        "Carlos",
        "Shane",
        "Aaron",
        "Marlin",
        "Paul",
        "Ricardo",
        "Hector",
        "Alexis",
        "Adrian",
        "Kingston",
        "Douglas",
        "Gerald",
        "Joey",
        "Johnny",
        "Charlie",
        "Scott",
        "Martin",
        "Tristin",
        "Troy",
        "Tommy",
        "Rick",
        "Victor",
        "Jessie",
        "Neil",
        "Ted",
        "Nick",
        "Wiley",
        "Morris",
        "Clark",
        "Stuart",
        "Orlando",
        "Keith",
        "Marion",
        "Marshall",
        "Noel",
        "Everett",
        "Romeo",
        "Sebastian",
        "Stefan",
        "Robin",
        "Clarence",
        "Sandy",
        "Ernest",
        "Samuel",
        "Benjamin",
        "Luka",
        "Fred",
        "Albert",
        "Greyson",
        "Terry",
        "Cedric",
        "Joe",
        "Paul",
        "George",
        "Bruce",
        "Christopher",
        "Mark",
        "Ron",
        "Craig",
        "Philip",
        "Jimmy",
        "Arthur",
        "Jaime",
        "Perry",
        "Harold",
        "Jerry",
        "Shawn",
        "Walter",
      ];
      let name = await names[Math.floor(Math.random() * names.length)];
      control.value = name;
      console.log(name);
    } else {
      console.log("no-name");
    }
  }
  function vote() {
    try {
      const votebtn = document.getElementById("vote_btn");
      votebtn.click();
      console.log("vote-btn-clicked");
    } catch (err) {}
  }

  async function refreshMe() {
    try {
      await sleep(15000);
      console.clear();
      if (document.getElementById("seconds_left")) {
        console.log("========================== refresh me in some time");
        let minutes = document.getElementById("minutes").textContent;
        let seconds = document.getElementById("seconds").textContent;
        /* let nxttime = document.getElementById("nxttime").textContent;
        nxttime = nxttime.replace(
          /(\d{1,2})\/(\d{1,2})\/(\d{4}),?/i,
          "$3-$2-$1"
        );
        const dateParts = nxttime.split(/[-/ :]/);
        const pm = dateParts.pop();
        dateParts[1]--;
        if (pm === "pm") {
          dateParts[3] = Number(dateParts[3]) + 12;
        }
        let dateObject = new Date(Date.UTC(...dateParts));
        dateObject.setMinutes(dateObject.getMinutes() + 1);

        let currentDate = new Date();
        console.log("===========dateObject", dateObject);
        console.log("===========currentDate", currentDate);
        const reloadTime = dateObject.getTime() - currentDate.getTime(); */
        const reloadTime = (minutes + 1) * 60 * 1000;
        console.log(`set reload timer for ${reloadTime}`);
        setTimeout(() => {
          window.location.reload();
        }, reloadTime);
      } else {
        console.log("========================== else refresh me");
        // refresh if vote was unsuccessful
        const vote_msg = document.getElementById("vote_msg");
        if (
          vote_msg.textContent.includes(
            "It looks like you have already voted one time in last 30 minute"
          )
        ) {
          window.location.reload();
        } else if (vote_msg.textContent.includes("TOR")) {
          window.close();
        }
      }
    } catch (err) {
      console.log("refreshMe", err);
    }
  }

  async function activate() {
    await scroll();
    if (namedVote) {
      await fillName();
    }
    await vote();
    refreshMe();
  }
  activate();
})();
