#!/bin/bash

cd ../my-user-scripts
cp ~/.bashrc .
cp ~/.config/Code/User/snippets/surjeet-global-snippet.code-snippets .
cp ~/.config/Code/User/keybindings.json .


git remote set-url --push origin ssh://git@gitlab.dyninno.net:1022/dreamport/mindtickle-analytics.git
git remote set-url --add --push origin https://github.com/surjeetindia/mindtickle-analytics.git

git remote get-url --push --all origin
git push --set-upstream origin master
git remote set-url --delete --push origin https://github.com/surjeetindia/mindtickle-analytics.git

git branch --unset-upstream
git branch --set-upstream-to=origin/master

git branch --set-upstream-to=origin/master master


gst
git pull
git add .
git cp 'updated-files'



cd ../mindtickle-v2
git remote add originn https://github.com/surjeetindia/mindtickle.git
git status
git checkout master
git pull
git push -u originn master
