import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
async function main() {
  await prisma.$queryRaw`SET FOREIGN_KEY_CHECKS=0`;
  await prisma.$queryRaw`truncate category`;
  await prisma.$queryRaw`truncate setting`;
  await prisma.$queryRaw`truncate settings`;
  await prisma.$queryRaw`truncate advertiser`;
  await prisma.$queryRaw`truncate profileState`;
  await prisma.$queryRaw`truncate profileOrigin`;
  await prisma.$queryRaw`truncate position`;
  await prisma.$queryRaw`truncate applicationStatus`;
  await prisma.$queryRaw`truncate educationLevel`;
  await prisma.$queryRaw`truncate experience`;
  await prisma.$queryRaw`truncate rejectReason`;
  await prisma.$queryRaw`truncate skill`;
  await prisma.$queryRaw`truncate location`;
  await prisma.$queryRaw`truncate language`;

  await prisma.location.createMany({
    data: [{ id: 1, name: 'DRP' }],
  });

  await prisma.category.createMany({
    data: [
      { name: 'registration', label: 'Registration', status: 1 },
      { name: 'assessment', label: 'Assessment', status: 1 },
      { name: 'training', label: 'Training', status: 1 },
      { name: 'system-links', label: 'System Links', status: 1 },
      { name: 'performance-rules', label: 'Performance Rules', status: 1 },
      { name: 'manual_documents', label: 'Documents', status: 1 },
      { name: 'exception-messages', label: 'Exception Messages', status: 1 },
      { name: 'news', label: 'News', status: 0 },
      { name: 'notifications', label: 'Notifications', status: 0 },
      { id: 10, name: 'settings', label: 'Settings', status: 0 },
    ],
  });

  await prisma.setting.createMany({
    data: [
      {
        categoryId: 5,
        key: 'RULES',
        value:
          '{"dos":["Be on time","Be polite","Consider timezone","Regular follow-up","Leave voicemails","Speak Speak positive","Listen carefully","Follow your promises","Provide best service","Look for best solution"],"donts":["Be on time","Be polite","Consider timezone","Regular follow-up","Leave voicemails","Speak positive","Listen carefully","Follow your promises","Provide best service","Look for best solution"]}',
        type: 'json',
        status: 1,
      },
      {
        categoryId: 4,
        key: 'LINKS',
        value:
          '[{"name":"CMS","link":"https://cms.asaptickets.com/calendar","imageLink":"https://attachment-storage.asaptickets.com/362/838/91b34fb22ee354427813ca8bbc92a18f.svg","style":{"height":"100","background":"#E7EAEE"}},{"name":"Calendar","link":"https://cms.asaptickets.com/calendar","imageLink":"https://attachment-storage.asaptickets.com/362/838/48bae00b8647bad681b92996dfabc74d.svg","style":{"height":"100","background":"rgba(255, 233, 181, 0.6)"}},{"name":"Invoicing","link":"https://cms.asaptickets.com","img":"https://www.google.com","imageLink":"https://attachment-storage.asaptickets.com/362/838/75dca6d8cadbe67eb2fbbb459c863a52.svg","style":{"height":"100","background":"#D9D5F9"}},{"name":"Gamification","link":"https://dreamcraft.asaptickets.com","imageLink":"https://attachment-storage.asaptickets.com/362/838/87970591db1efda139c7df2c035948dd.svg","style":{"height":"100","background":"rgba(255, 195, 212, 0.5)"}},{"name":"Performance","link":"https://cms.asaptickets.com/statistic/agents","imageLink":"https://attachment-storage.asaptickets.com/362/838/d17a0ddeca85e51a86ce517bafa61940.svg","style":{"height":"100","background":"rgba(255, 233, 181, 0.6)"}},{"name":"test","link":"testlink"}]',
        type: 'json',
        status: 1,
      },
      {
        categoryId: 6,
        key: 'DOCS',
        value:
          '[{"name":"GBO manual is too good","link":"https://www.google.co.in/"},{"name":"DynaCraft manual","link":"https://www.google.co.in/"},{"name":"GDS manual","link":"https://www.google.co.in/"},{"name":"ProQuote manual","link":"https://www.google.co.in/"},{"name":"DreamPort manual","link":"https://www.google.co.in/"}]',
        type: 'json',
        status: 1,
      },
      {
        categoryId: 7,
        key: 'EXCEPMSG',
        value:
          '[{"key":"REGISTER.INVALID_FNAME","value":"Invalid first Name"},{"key":"ASSESSMENT.INELIGIBLE","value":"You are not eligible to take the test"}]',
        type: 'json',
        status: 1,
      },
      {
        categoryId: 10,
        key: 'SETTING',
        value:
          '[{"training":{"waitingDays":1,"trainingApplicable":false,"passScreenText":""},"assessment":{"minPassPercentage":90,"assessmentIds":[{"ids":[871725]}],"legacyAssessmentIds":[0],"assessmentApplicable":true,"passScreenText":"","rejectionDays":7},"registration":{"userTotalAttempt":1,"userAttemptDayGap":1,"hrTotalAttempt":1,"hrAttemptDayGap":0,"countries":[105],"position":[{"id":3,"name":"Customer Service Consultant"}],"settingName":"Customer Service Consultant"}},{"training":{"waitingDays":15,"trainingApplicable":true,"passScreenText":""},"assessment":{"minPassPercentage":40,"assessmentIds":[{"ids":[871725,872028]},{"ids":[872028,871725]}],"legacyAssessmentIds":[0],"assessmentApplicable":true,"passScreenText":"","rejectionDays":30},"registration":{"userTotalAttempt":2,"userAttemptDayGap":90,"hrTotalAttempt":2,"hrAttemptDayGap":0,"countries":[65,105,140],"position":[{"id":1,"name":"Independant Travel Manager"}],"settingName":"Independent Travel Manager"}},{"training":{"waitingDays":0,"trainingApplicable":false,"passScreenText":""},"assessment":{"minPassPercentage":40,"assessmentIds":[{"ids":[871725]}],"legacyAssessmentIds":[0],"assessmentApplicable":true,"passScreenText":"","rejectionDays":7},"registration":{"userTotalAttempt":1,"userAttemptDayGap":90,"hrTotalAttempt":1,"hrAttemptDayGap":0,"countries":[65,105],"position":[{"id":59,"name":"Customer Service Consultant (OOJO)"}],"settingName":"Customer Service Consultant (OOJO)"}},{"training":{"waitingDays":0,"trainingApplicable":false,"passScreenText":""},"assessment":{"minPassPercentage":40,"assessmentIds":[{"ids":[871725]}],"legacyAssessmentIds":[0],"assessmentApplicable":true,"passScreenText":"","rejectionDays":7},"registration":{"userTotalAttempt":1,"userAttemptDayGap":90,"hrTotalAttempt":1,"hrAttemptDayGap":0,"countries":[65,105],"position":[{"id":61,"name":"Dedicated Customer Solutions (Re-Protection) Consultant"}],"settingName":"Dedicated Customer Solutions (Re-Protection) Consultant"}}]',
        type: 'json',
        status: 1,
      },
    ],
  });

  await prisma.settingNames.createMany({
    data: [
      {
        id: 1,
        name: '',
        status: 1,
        createdAt: '2024-11-11T02:08:19.000Z',
        updatedAt: '2024-11-11T03:28:58.000Z',
      },
    ],
  });

  await prisma.settingPositions.createMany({
    data: [
      {
        id: 1,
        settingNameId: 1,
        positionId: 1,
        area: 1,
      },
    ],
  });

  await prisma.settings.createMany({
    data: [
      {
        id: 1,
        settingNameId: 1,
        key: 'cities',
        value: '[]',
        type: null,
        desc: null,
        status: 1,
        invert: null,
        createdAt: '2024-11-11T02:08:19.000Z',
        updatedAt: '2024-11-11T03:28:58.000Z',
      },
      {
        id: 2,
        settingNameId: 1,
        key: 'states',
        value: '[]',
        type: null,
        desc: null,
        status: 1,
        invert: null,
        createdAt: '2024-11-11T02:08:19.000Z',
        updatedAt: '2024-11-11T03:28:58.000Z',
      },
      {
        id: 3,
        settingNameId: 1,
        key: 'countries',
        value:
          '[3,15,6,62,11,1,8,5,9,4,10,7,14,13,12,16,32,23,19,18,20,37,25,27,33,29,30,17,35,34,31,106,240,28,22,21,24,52,117,47,38,125,41,216,46,48,54,39,49,119,45,50,98,51,53,55,56,40,59,58,60,61,63,65,211,88,64,214,69,72,74,71,70,75,80,176,217,76,85,79,57,82,83,89,84,78,87,92,91,81,86,93,94,99,96,97,95,100,109,101,107,102,104,103,110,44,112,114,111,113,126,115,118,123,124,116,127,136,128,133,132,137,130,134,135,149,143,157,159,156,146,154,144,151,152,155,247,158,73,140,139,148,141,153,138,160,147,161,170,169,252,162,172,166,163,165,171,164,145,150,168,173,179,186,184,174,177,187,175,178,182,180,185,183,188,42,189,190,193,26,201,120,129,142,181,238,245,206,210,194,207,191,251,196,205,200,212,204,202,195,208,248,90,122,68,131,209,203,199,43,213,229,220,230,219,167,222,218,221,225,227,224,226,223,215,228,241,232,231,77,234,233,235,236,243,237,242,244,246,249,250,105]',
        type: null,
        desc: null,
        status: 1,
        invert: null,
        createdAt: '2024-11-11T02:08:19.000Z',
        updatedAt: '2024-11-11T03:28:58.000Z',
      },
    ],
  });

  await prisma.advertiser.createMany({
    data: [
      { id: 1, name: 'DreamPort' },
      { id: 2, name: 'Facebook' },
      { id: 3, name: 'Linked-In' },
      { id: 4, name: 'Instagram' },
      { id: 5, name: 'Twitter' },
    ],
  });

  await prisma.profileState.createMany({
    data: [
      { id: 1, name: 'applicant' },
      { id: 2, name: 'ex-applicant' },
      { id: 3, name: 'employee' },
      { id: 4, name: 'ex-employee' },
    ],
  });

  await prisma.profileOrigin.createMany({
    data: [
      { id: 1, name: 'DRPT' },
      { id: 2, name: 'PUB' },
      { id: 3, name: 'Other' },
      { id: 4, name: 'HRM' },
    ],
  });

  await prisma.position.createMany({
    data: [
      { name: 'Independent travel manager' },
      { name: 'Chat Independent travel manager' },
      { name: 'Customer Service Consultant' },
    ],
  });

  await prisma.applicationStatus.createMany({
    data: [
      { name: 'APPLICATION_REJECTED', id: -2 },
      { name: 'APPLICATION_REJECTED_HR', id: -3 },
      { name: 'ACCOUNT_BLOCKED', id: -1 },
      { name: 'APPLICATION_DEACTIVATED_BY_SYSTEM', id: -4 },
      { name: 'APPLICATION_REGISTERED', id: 2 },
      { name: 'PROFILE_LOGGED_IN', id: 222 },
      { name: 'ASSESSMENT_READY', id: 3 },
      { name: 'ASSESSMENT_IN_PROGRESS', id: 4 },
      { name: 'ASSESSMENT_SUBMIT_RESPONSE_AWAITED', id: 8 },
      { name: 'ASSESSMENT_FAILED_ATTEMPT_LEFT', id: 7 },
      { name: 'ASSESSMENT_PASSED', id: 6 },
      { name: 'ASSESSMENT_FAILED_NO_ATTEMPT_LEFT', id: 5 },
      { name: 'TRAINING_READY', id: 17 },
      { name: 'TRAINING_INITIATED', id: 9 },
      { name: 'TRAINING_INITIATED_BY_USER', id: 18 },
      { name: 'TRAINING_IN_PROGRESS', id: 10 },
      { name: 'TRAINING_CERT_AWAITED', id: 16 },
      { name: 'TRAINING_PASSED', id: 11 },
      { name: 'TRAINING_FAILED_ATTEMPT_LEFT', id: 12 },
      { name: 'TRAINING_FAILED_NO_ATTEMPT_LEFT', id: 13 },
      { name: 'NICK_NAME_SELECTION', id: 14 },
      { name: 'WORK_HOURS_SELECTION', id: 15 },
      { name: 'TRAINING_TUTORIAL_WATCHED', id: 19 },
      { name: 'TRAINING_ONBOARDING', id: 20 },
      { name: 'TRAINING_PRE_LIVE_READY', id: 21 },
      { name: 'TRAINING_PRE_LIVE_INITIATED', id: 22 },
      { name: 'TRAINING_PRE_LIVE_IN_PROGRESS', id: 23 },
      { name: 'TRAINING_PRE_LIVE_PASSED', id: 24 },
      { name: 'TRAINING_PRE_LIVE_FAILED', id: 25 },
      { name: 'CONTRACT_PENDING', id: 31 },
      { name: 'CONTRACT_ON_GOING', id: 32 },
      { name: 'CONTRACTED', id: 33 },
      { name: 'TERMINATED', id: 34 },
    ],
  });

  await prisma.educationLevel.createMany({
    data: [
      { name: 'School' },
      { name: 'Professional' },
      { name: 'College' },
      { name: 'Bachelor' },
      { name: 'Masters' },
      { name: 'Post-University' },
      { name: 'Doctorate' },
    ],
  });

  await prisma.experience.createMany({
    data: [
      { name: 'No experience' },
      { name: '<1 year' },
      { name: '1-3 years' },
      { name: '3-5 years' },
      { name: '5+ years' },
    ],
  });

  await prisma.rejectReason.createMany({
    data: [
      { id: 16, name: 'Rejected by Manager' },
      { id: 17, name: 'Rejected by Trainer' },
      { id: 18, name: 'Rejected by HR' },
      { id: 19, name: 'Rejected by Applicant' },
      { id: 20, name: 'Missed training' },
      { id: 21, name: 'Missed re-training' },
      { id: 22, name: 'Missed interview' },
      { id: 23, name: 'Quit' },
      { id: 24, name: 'Fired' },
      { id: 25, name: 'Retired' },
      { id: 40, name: 'Default Reject Reason' },
      { id: 87, name: 'Does not like the job' },
      { id: 88, name: 'No base salary' },
      { id: 89, name: 'Bad reviews or feedback about the Company' },
      { id: 90, name: 'Found another job' },
      { id: 91, name: 'Bad Training experience' },
      { id: 92, name: 'Cannot assimilate the information/training too quick' },
      { id: 93, name: 'No Support from the trainer' },
      { id: 94, name: 'Disappeared/No Feedback' },
      { id: 95, name: 'Other' },
      { id: 96, name: 'No time slots that suit' },
      { id: 97, name: 'Bad customer experience' },
      { id: 98, name: 'No support from the Mentor' },
      { id: 99, name: 'Does not like teammates' },
    ],
  });

  await prisma.rejectReasonStage.createMany({
    data: [
      { stageId: 1, rejectReasonId: 87 },
      { stageId: 1, rejectReasonId: 88 },
      { stageId: 1, rejectReasonId: 89 },
      { stageId: 1, rejectReasonId: 90 },
      { stageId: 1, rejectReasonId: 95 },
      { stageId: 1, rejectReasonId: 97 },
      { stageId: 1, rejectReasonId: 99 },
      { stageId: 2, rejectReasonId: 87 },
      { stageId: 2, rejectReasonId: 88 },
      { stageId: 2, rejectReasonId: 89 },
      { stageId: 2, rejectReasonId: 90 },
      { stageId: 2, rejectReasonId: 92 },
      { stageId: 2, rejectReasonId: 93 },
      { stageId: 2, rejectReasonId: 95 },
      { stageId: 2, rejectReasonId: 97 },
      { stageId: 2, rejectReasonId: 99 },
      { stageId: 3, rejectReasonId: 16 },
      { stageId: 3, rejectReasonId: 17 },
      { stageId: 3, rejectReasonId: 18 },
      { stageId: 3, rejectReasonId: 19 },
      { stageId: 3, rejectReasonId: 20 },
      { stageId: 3, rejectReasonId: 21 },
      { stageId: 3, rejectReasonId: 22 },
      { stageId: 3, rejectReasonId: 23 },
      { stageId: 3, rejectReasonId: 24 },
      { stageId: 3, rejectReasonId: 25 },
      { stageId: 3, rejectReasonId: 40 },
      { stageId: 3, rejectReasonId: 87 },
      { stageId: 3, rejectReasonId: 88 },
      { stageId: 3, rejectReasonId: 89 },
      { stageId: 3, rejectReasonId: 90 },
      { stageId: 3, rejectReasonId: 91 },
      { stageId: 3, rejectReasonId: 92 },
      { stageId: 3, rejectReasonId: 93 },
      { stageId: 3, rejectReasonId: 95 },
      { stageId: 3, rejectReasonId: 96 },
      { stageId: 3, rejectReasonId: 97 },
      { stageId: 3, rejectReasonId: 98 },
      { stageId: 3, rejectReasonId: 99 },
    ],
  });

  await prisma.skill.createMany({
    data: [
      { id: 1, name: 'Account Management' },
      { id: 2, name: 'Accounting' },
      { id: 3, name: 'Analytical Skills' },
      { id: 4, name: 'Banking' },
      { id: 5, name: 'Budgeting' },
      { id: 6, name: 'Business Development' },
      { id: 7, name: 'Business Intelligence' },
      { id: 8, name: 'Business Process Outsourcing (BPO/Call Center)' },
      { id: 9, name: 'Coaching' },
      { id: 10, name: 'Communication' },
      { id: 11, name: 'Continuous Improvement' },
      { id: 12, name: 'Customer Relationship Management' },
      { id: 13, name: 'Customer Service' },
      { id: 14, name: 'Data Analysis' },
      { id: 15, name: 'Data Entry' },
      { id: 16, name: 'E-Commerce' },
      { id: 17, name: 'Entrepreneurship' },
      { id: 18, name: 'Financial Analysis' },
      { id: 19, name: 'Hospitality' },
      { id: 20, name: 'Hotel Management' },
      { id: 21, name: 'Human Resource Management' },
      { id: 22, name: 'Key Account Development' },
      { id: 23, name: 'Lead Generation' },
      { id: 24, name: 'Leadership' },
      { id: 25, name: 'Leadership Development' },
      { id: 26, name: 'Management' },
      { id: 27, name: 'Marketing' },
      { id: 28, name: 'Negotiation' },
      { id: 29, name: 'Networking' },
      { id: 30, name: 'Online Advertising' },
      { id: 31, name: 'Online Marketing' },
      { id: 32, name: 'Operations Management' },
      { id: 33, name: 'Organizational Development' },
      { id: 34, name: 'Project Management' },
      { id: 35, name: 'Project Planning' },
      { id: 36, name: 'Public Relations' },
      { id: 37, name: 'Public Speaking' },
      { id: 38, name: 'Quality Assurance' },
      { id: 39, name: 'Recruiting' },
      { id: 40, name: 'Retail' },
      { id: 41, name: 'Risk Management' },
      { id: 42, name: 'Sales' },
      { id: 43, name: 'Sales Management' },
      { id: 44, name: 'Sales Operations' },
      { id: 45, name: 'Social Media Marketing' },
      { id: 46, name: 'Strategic Planning' },
      { id: 47, name: 'Team Building' },
      { id: 48, name: 'Team Leadership' },
      { id: 49, name: 'Team Management' },
      { id: 50, name: 'Teamwork' },
      { id: 51, name: 'Telecommunications' },
      { id: 52, name: 'Time Management' },
      { id: 53, name: 'Training' },
      { id: 54, name: 'Global Distribution System' },
      { id: 55, name: 'Client Management System' },
    ],
  });

  await prisma.language.createMany({
    data: [
      { id: 1, name: 'Afar', code: 'aar', iso: null },
      { id: 3, name: 'Abkhaz', code: 'abk', iso: null },
      { id: 5, name: 'Afrikaans', code: 'afr', iso: null },
      { id: 7, name: 'Akan', code: 'aka', iso: null },
      { id: 9, name: 'Amharic', code: 'amh', iso: null },
      { id: 11, name: 'Aragonese', code: 'arg', iso: null },
      { id: 13, name: 'Arabic', code: 'ara', iso: null },
      { id: 15, name: 'Assamese', code: 'asm', iso: null },
      { id: 17, name: 'Avaric', code: 'ava', iso: null },
      { id: 19, name: 'Aymara', code: 'aym', iso: null },
      { id: 21, name: 'Azerbaijani', code: 'aze', iso: null },
      { id: 23, name: 'Bashkir', code: 'bak', iso: null },
      { id: 25, name: 'Belarusian', code: 'bel', iso: null },
      { id: 27, name: 'Bulgarian', code: 'bul', iso: null },
      { id: 29, name: 'Bislama', code: 'bis', iso: null },
      { id: 31, name: 'Bambara', code: 'bam', iso: null },
      { id: 33, name: 'Bengali', code: 'ben', iso: null },
      { id: 35, name: 'Tibetan', code: 'bod', iso: null },
      { id: 37, name: 'Breton', code: 'bre', iso: null },
      { id: 39, name: 'Bosnian', code: 'bos', iso: null },
      { id: 41, name: 'Catalan', code: 'cat', iso: null },
      { id: 43, name: 'Chechen', code: 'che', iso: null },
      { id: 45, name: 'Chamorro', code: 'cha', iso: null },
      { id: 47, name: 'Corsican', code: 'cos', iso: null },
      { id: 49, name: 'Cree', code: 'cre', iso: null },
      { id: 51, name: 'Czech', code: 'ces', iso: null },
      { id: 53, name: 'Chuvash', code: 'chv', iso: null },
      { id: 55, name: 'Welsh', code: 'cym', iso: null },
      { id: 57, name: 'Danish', code: 'dan', iso: null },
      { id: 59, name: 'German', code: 'deu', iso: null },
      { id: 61, name: 'Dhivehi', code: 'div', iso: null },
      { id: 63, name: 'Dzongkha', code: 'dzo', iso: null },
      { id: 65, name: 'Ewe', code: 'ewe', iso: null },
      { id: 67, name: 'Greek', code: 'ell', iso: null },
      { id: 69, name: 'English', code: 'eng', iso: null },
      { id: 71, name: 'Spanish', code: 'spa', iso: null },
      { id: 73, name: 'Estonian', code: 'est', iso: null },
      { id: 75, name: 'Basque', code: 'eus', iso: null },
      { id: 77, name: 'Persian', code: 'fas', iso: null },
      { id: 79, name: 'Fula', code: 'ful', iso: null },
      { id: 81, name: 'Finnish', code: 'fin', iso: null },
      { id: 83, name: 'Fijian', code: 'fij', iso: null },
      { id: 85, name: 'Faroese', code: 'fao', iso: null },
      { id: 87, name: 'French', code: 'fra', iso: null },
      { id: 89, name: 'Western Frisian', code: 'fry', iso: null },
      { id: 91, name: 'Irish', code: 'gle', iso: null },
      { id: 93, name: 'Scottish Gaelic', code: 'gla', iso: null },
      { id: 95, name: 'Galician', code: 'glg', iso: null },
      { id: 97, name: 'Guarani', code: 'grn', iso: null },
      { id: 99, name: 'Gujarati', code: 'guj', iso: null },
      { id: 101, name: 'Manx', code: 'glv', iso: null },
      { id: 103, name: 'Hausa', code: 'hau', iso: null },
      { id: 105, name: 'Hebrew', code: 'heb', iso: null },
      { id: 107, name: 'Hindi', code: 'hin', iso: null },
      { id: 109, name: 'Hiri Motu', code: 'hmo', iso: null },
      { id: 111, name: 'Croatian', code: 'hrv', iso: null },
      { id: 113, name: 'Haitian', code: 'hat', iso: null },
      { id: 115, name: 'Hungarian', code: 'hun', iso: null },
      { id: 117, name: 'Armenian', code: 'hye', iso: null },
      { id: 119, name: 'Herero', code: 'her', iso: null },
      { id: 121, name: 'Indonesian', code: 'ind', iso: null },
      { id: 123, name: 'Igbo', code: 'ibo', iso: null },
      { id: 125, name: 'Nuosu', code: 'iii', iso: null },
      { id: 127, name: 'Inupiaq', code: 'ipk', iso: null },
      { id: 129, name: 'Icelandic', code: 'isl', iso: null },
      { id: 131, name: 'Italian', code: 'ita', iso: null },
      { id: 133, name: 'Inuktitut', code: 'iku', iso: null },
      { id: 135, name: 'Japanese', code: 'jpn', iso: null },
      { id: 137, name: 'Javanese', code: 'jav', iso: null },
      { id: 139, name: 'Georgian', code: 'kat', iso: null },
      { id: 141, name: 'Kongo', code: 'kon', iso: null },
      { id: 143, name: 'Gikuyu', code: 'kik', iso: null },
      { id: 145, name: 'Kwanyama', code: 'kua', iso: null },
      { id: 147, name: 'Kazakh', code: 'kaz', iso: null },
      { id: 149, name: 'Kalaallisut', code: 'kal', iso: null },
      { id: 151, name: 'Khmer', code: 'khm', iso: null },
      { id: 153, name: 'Kannada', code: 'kan', iso: null },
      { id: 155, name: 'Korean', code: 'kor', iso: null },
      { id: 157, name: 'Kanuri', code: 'kau', iso: null },
      { id: 159, name: 'Kashmiri', code: 'kas', iso: null },
      { id: 161, name: 'Kurdish', code: 'kur', iso: null },
      { id: 163, name: 'Komi', code: 'kom', iso: null },
      { id: 165, name: 'Cornish', code: 'cor', iso: null },
      { id: 167, name: 'Kyrgyz', code: 'kir', iso: null },
      { id: 169, name: 'Luxembourgish', code: 'ltz', iso: null },
      { id: 171, name: 'Ganda', code: 'lug', iso: null },
      { id: 173, name: 'Limburgan', code: 'lim', iso: null },
      { id: 175, name: 'Lingala', code: 'lin', iso: null },
      { id: 177, name: 'Lao', code: 'lao', iso: null },
      { id: 179, name: 'Lithuanian', code: 'lit', iso: null },
      { id: 181, name: 'Luba-Katanga', code: 'lub', iso: null },
      { id: 183, name: 'Latvian', code: 'lav', iso: null },
      { id: 185, name: 'Malagasy', code: 'mlg', iso: null },
      { id: 187, name: 'Marshallese', code: 'mah', iso: null },
      { id: 189, name: 'Maori', code: 'mri', iso: null },
      { id: 191, name: 'Macedonian', code: 'mkd', iso: null },
      { id: 193, name: 'Malayalam', code: 'mal', iso: null },
      { id: 195, name: 'Mongolian', code: 'mon', iso: null },
      { id: 197, name: 'Marathi', code: 'mar', iso: null },
      { id: 199, name: 'Malay', code: 'msa', iso: null },
      { id: 201, name: 'Maltese', code: 'mlt', iso: null },
      { id: 203, name: 'Burmese', code: 'mya', iso: null },
      { id: 205, name: 'Nauru', code: 'nau', iso: null },
      { id: 207, name: 'Norwegian Bokmål', code: 'nob', iso: null },
      { id: 209, name: 'Northern Ndebele', code: 'nde', iso: null },
      { id: 211, name: 'Nepali', code: 'nep', iso: null },
      { id: 213, name: 'Ndonga', code: 'ndo', iso: null },
      { id: 215, name: 'Dutch', code: 'nld', iso: null },
      { id: 217, name: 'Norwegian Nynorsk', code: 'nno', iso: null },
      { id: 219, name: 'Norwegian', code: 'nor', iso: null },
      { id: 221, name: 'Southern Ndebele', code: 'nbl', iso: null },
      { id: 223, name: 'Navajo', code: 'nav', iso: null },
      { id: 225, name: 'Nyanja', code: 'nya', iso: null },
      { id: 227, name: 'Occitan', code: 'oci', iso: null },
      { id: 229, name: 'Ojibwa', code: 'oji', iso: null },
      { id: 231, name: 'Oromo', code: 'orm', iso: null },
      { id: 233, name: 'Oriya', code: 'ori', iso: null },
      { id: 235, name: 'Ossetian', code: 'oss', iso: null },
      { id: 237, name: 'Punjabi', code: 'pan', iso: null },
      { id: 239, name: 'Polish', code: 'pol', iso: null },
      { id: 241, name: 'Pashto', code: 'pus', iso: null },
      { id: 243, name: 'Portuguese', code: 'por', iso: null },
      { id: 245, name: 'Quechua', code: 'que', iso: null },
      { id: 247, name: 'Romansh', code: 'roh', iso: null },
      { id: 249, name: 'Kirundi', code: 'run', iso: null },
      { id: 251, name: 'Romanian', code: 'ron', iso: null },
      { id: 253, name: 'Russian', code: 'rus', iso: null },
      { id: 255, name: 'Kinyarwanda', code: 'kin', iso: null },
      { id: 257, name: 'Sardinian', code: 'srd', iso: null },
      { id: 259, name: 'Sindhi', code: 'snd', iso: null },
      { id: 261, name: 'Northern Sami', code: 'sme', iso: null },
      { id: 263, name: 'Sango', code: 'sag', iso: null },
      { id: 265, name: 'Sinhala', code: 'sin', iso: null },
      { id: 267, name: 'Slovak', code: 'slk', iso: null },
      { id: 269, name: 'Slovene', code: 'slv', iso: null },
      { id: 271, name: 'Samoan', code: 'smo', iso: null },
      { id: 273, name: 'Shona', code: 'sna', iso: null },
      { id: 275, name: 'Somali', code: 'som', iso: null },
      { id: 277, name: 'Albanian', code: 'sqi', iso: null },
      { id: 279, name: 'Serbian', code: 'srp', iso: null },
      { id: 281, name: 'Swati', code: 'ssw', iso: null },
      { id: 283, name: 'Southern Sotho', code: 'sot', iso: null },
      { id: 285, name: 'Sundanese', code: 'sun', iso: null },
      { id: 287, name: 'Swedish', code: 'swe', iso: null },
      { id: 289, name: 'Swahili', code: 'swa', iso: null },
      { id: 291, name: 'Tamil', code: 'tam', iso: null },
      { id: 293, name: 'Telugu', code: 'tel', iso: null },
      { id: 295, name: 'Tajik', code: 'tgk', iso: null },
      { id: 297, name: 'Thai', code: 'tha', iso: null },
      { id: 299, name: 'Tigrinya', code: 'tir', iso: null },
      { id: 301, name: 'Turkmen', code: 'tuk', iso: null },
      { id: 303, name: 'Tagalog', code: 'tgl', iso: null },
      { id: 305, name: 'Tswana', code: 'tsn', iso: null },
      { id: 307, name: 'Tongan', code: 'ton', iso: null },
      { id: 309, name: 'Turkish', code: 'tur', iso: null },
      { id: 311, name: 'Tsonga', code: 'tso', iso: null },
      { id: 313, name: 'Tatar', code: 'tat', iso: null },
      { id: 315, name: 'Twi', code: 'twi', iso: null },
      { id: 317, name: 'Tahitian', code: 'tah', iso: null },
      { id: 319, name: 'Uyghur', code: 'uig', iso: null },
      { id: 321, name: 'Ukrainian', code: 'ukr', iso: null },
      { id: 323, name: 'Urdu', code: 'urd', iso: null },
      { id: 325, name: 'Uzbek', code: 'uzb', iso: null },
      { id: 327, name: 'Venda', code: 'ven', iso: null },
      { id: 329, name: 'Vietnamese', code: 'vie', iso: null },
      { id: 331, name: 'Walloon', code: 'wln', iso: null },
      { id: 333, name: 'Wolof', code: 'wol', iso: null },
      { id: 335, name: 'Xhosa', code: 'xho', iso: null },
      { id: 337, name: 'Yiddish', code: 'yid', iso: null },
      { id: 339, name: 'Yoruba', code: 'yor', iso: null },
      { id: 341, name: 'Zhuang', code: 'zha', iso: null },
      { id: 343, name: 'Chinese', code: 'zho', iso: null },
      { id: 345, name: 'Zulu', code: 'zul', iso: null },
      { id: 482, name: 'Abkhazian', code: 'ab', iso: null },
      { id: 483, name: 'Bihari', code: 'bh', iso: null },
      { id: 484, name: 'Cambodian', code: 'km', iso: null },
      { id: 485, name: 'Esperanto', code: 'eo', iso: null },
      { id: 489, name: 'Interlingua', code: 'ia', iso: null },
      { id: 490, name: 'Interlingue', code: 'ie', iso: null },
      { id: 492, name: 'Kirghiz', code: 'ky', iso: null },
      { id: 494, name: 'Latin', code: 'la', iso: null },
      { id: 495, name: 'Moldavian', code: 'mo', iso: null },
      { id: 497, name: 'Sanskrit', code: 'sa', iso: null },
      { id: 498, name: 'Serbo-Croatian', code: 'sh', iso: null },
      { id: 499, name: 'Sesotho', code: 'st', iso: null },
      { id: 500, name: 'Slovenian', code: 'sl', iso: null },
      { id: 501, name: 'Tonga', code: 'to', iso: null },
      { id: 502, name: 'Volapuk', code: 'vo', iso: null },
    ],
  });

  await prisma.contract.createMany({
    data: [
      { id: 1, name: 'Dreamport LLP' },
      { id: 2, name: 'Dyninno Dreamport Inc' },
    ],
  });
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async e => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
